/** Demo fixtures for the Org Console — Hope Forward International (Pilot-Charlie). */

export const TODAY_KPIS = {
  knocksToday: 1247,
  knocksDelta: '+8.4%',
  conversionsToday: 184,
  conversionsDelta: '+12.1%',
  conversionRate: 14.8,
  conversionRateDelta: '+0.6pp',
  revenueTodayCents: 64_220_00n,
  revenueDelta: '+18.2%',
};

export const ANOMALIES = [
  {
    severity: 'critical' as const,
    title: '17 missed callbacks past SLA',
    description:
      'Callbacks promised for today 14:00–17:00 not yet contacted. Reassign or auto-dial?',
    timestamp: '15m ago',
  },
  {
    severity: 'warning' as const,
    title: 'Austin-East-Residential conversion 4.2% — below 9% baseline',
    description: 'Two knockers report unusual resistance. Check pitch script + DNC overlap.',
    timestamp: '1h ago',
  },
  {
    severity: 'info' as const,
    title: 'Top knocker: Jordan M · 31 conversions today',
    description: '$8,940 of recurring giving in one shift. Recognise on next leaderboard.',
    timestamp: '2h ago',
  },
  {
    severity: 'warning' as const,
    title: '3 knockers idle past shift-start',
    description: 'Kim P, Marcus L, Devon R — no clock-in by 09:30. SMS sent.',
    timestamp: '3h ago',
  },
];

export const TERRITORIES = [
  {
    id: 'ter_austin_east',
    name: 'Austin East Residential',
    knockers: 8,
    doorsTotal: 3240,
    doorsKnocked: 1890,
    conversionRate: 4.2,
    state: 'TX',
    cleared: true,
  },
  {
    id: 'ter_austin_north',
    name: 'Austin North',
    knockers: 6,
    doorsTotal: 2850,
    doorsKnocked: 2210,
    conversionRate: 9.8,
    state: 'TX',
    cleared: true,
  },
  {
    id: 'ter_dallas_metro',
    name: 'Dallas Metro',
    knockers: 12,
    doorsTotal: 5140,
    doorsKnocked: 4290,
    conversionRate: 11.4,
    state: 'TX',
    cleared: true,
  },
  {
    id: 'ter_houston_se',
    name: 'Houston Southeast',
    knockers: 9,
    doorsTotal: 4120,
    doorsKnocked: 1840,
    conversionRate: 8.9,
    state: 'TX',
    cleared: true,
  },
  {
    id: 'ter_phoenix_west',
    name: 'Phoenix West',
    knockers: 7,
    doorsTotal: 3580,
    doorsKnocked: 920,
    conversionRate: 12.1,
    state: 'AZ',
    cleared: true,
  },
  {
    id: 'ter_atlanta_north',
    name: 'Atlanta North',
    knockers: 10,
    doorsTotal: 4490,
    doorsKnocked: 3280,
    conversionRate: 10.2,
    state: 'GA',
    cleared: true,
  },
  {
    id: 'ter_la_west',
    name: 'LA West (BLOCKED)',
    knockers: 0,
    doorsTotal: 5290,
    doorsKnocked: 0,
    conversionRate: 0,
    state: 'CA',
    cleared: false,
  },
];

export const LEADS = [
  {
    name: 'Maria Santos',
    status: 'new',
    source: 'door',
    address: '4218 Lakeview Dr, Austin TX',
    phone: '+15125550182',
    assignee: 'JD',
    tier: 'high',
  },
  {
    name: 'David Chen',
    status: 'contacted',
    source: 'door',
    address: '887 Maple Ave, Dallas TX',
    phone: '+12145550293',
    assignee: 'AM',
    tier: 'high',
  },
  {
    name: 'Aisha Williams',
    status: 'qualified',
    source: 'retargeting',
    address: '1502 Cedar St, Austin TX',
    phone: '+15125550441',
    assignee: 'JD',
    tier: 'medium',
  },
  {
    name: 'Robert Kim',
    status: 'appointment_set',
    source: 'inside_sales',
    address: '3098 Birch Ln, Houston TX',
    phone: '+17135550568',
    assignee: 'TM',
    tier: 'high',
  },
  {
    name: 'Jennifer López',
    status: 'converted',
    source: 'door',
    address: '2204 Oak St, Phoenix AZ',
    phone: '+16025550712',
    assignee: 'JD',
    tier: 'high',
  },
  {
    name: 'Marcus Brown',
    status: 'lost',
    source: 'retargeting',
    address: '1855 Pine Rd, Atlanta GA',
    phone: '+14045550819',
    assignee: 'AM',
    tier: 'low',
  },
  {
    name: 'Sophia Patel',
    status: 'contacted',
    source: 'door',
    address: '4502 Walnut Cir, Atlanta GA',
    phone: '+14045550923',
    assignee: 'TM',
    tier: 'medium',
  },
  {
    name: 'Kevin Murphy',
    status: 'new',
    source: 'door',
    address: '729 Elm Pl, Dallas TX',
    phone: '+12145551034',
    assignee: '',
    tier: 'medium',
  },
];

export const PIPELINE_STAGES = [
  { stage: 'New', count: 38, valueCents: 12_400_00n },
  { stage: 'Contacted', count: 26, valueCents: 9_180_00n },
  { stage: 'Qualified', count: 19, valueCents: 8_240_00n },
  { stage: 'Appointment set', count: 12, valueCents: 6_120_00n },
  { stage: 'Converted', count: 184, valueCents: 64_220_00n },
];

export const KNOCKERS = [
  {
    name: 'Jordan Mosley',
    initials: 'JM',
    knocks: 84,
    conversions: 31,
    conversionRate: 36.9,
    revenueCents: 8_940_00n,
    status: 'active',
  },
  {
    name: 'Aaliyah Reed',
    initials: 'AR',
    knocks: 78,
    conversions: 18,
    conversionRate: 23.1,
    revenueCents: 5_420_00n,
    status: 'active',
  },
  {
    name: 'Devon Russell',
    initials: 'DR',
    knocks: 0,
    conversions: 0,
    conversionRate: 0,
    revenueCents: 0n,
    status: 'idle',
  },
  {
    name: 'Marcus Lee',
    initials: 'ML',
    knocks: 0,
    conversions: 0,
    conversionRate: 0,
    revenueCents: 0n,
    status: 'idle',
  },
  {
    name: 'Tomás Mendez',
    initials: 'TM',
    knocks: 72,
    conversions: 14,
    conversionRate: 19.4,
    revenueCents: 4_180_00n,
    status: 'active',
  },
  {
    name: 'Kim Park',
    initials: 'KP',
    knocks: 0,
    conversions: 0,
    conversionRate: 0,
    revenueCents: 0n,
    status: 'idle',
  },
  {
    name: 'Asha Mehta',
    initials: 'AM',
    knocks: 66,
    conversions: 12,
    conversionRate: 18.2,
    revenueCents: 3_640_00n,
    status: 'active',
  },
  {
    name: 'Jada Davis',
    initials: 'JD',
    knocks: 91,
    conversions: 22,
    conversionRate: 24.2,
    revenueCents: 6_810_00n,
    status: 'active',
  },
];

export const COMMISSIONS = [
  {
    knocker: 'Jordan Mosley',
    initials: 'JM',
    baseCents: 84_000n,
    conversionsCents: 1_240_00n,
    totalCents: 2_080_00n,
    payoutBatch: 'PAY-2026-05A',
  },
  {
    knocker: 'Jada Davis',
    initials: 'JD',
    baseCents: 91_000n,
    conversionsCents: 880_00n,
    totalCents: 1_790_00n,
    payoutBatch: 'PAY-2026-05A',
  },
  {
    knocker: 'Aaliyah Reed',
    initials: 'AR',
    baseCents: 78_000n,
    conversionsCents: 720_00n,
    totalCents: 1_500_00n,
    payoutBatch: 'PAY-2026-05A',
  },
  {
    knocker: 'Tomás Mendez',
    initials: 'TM',
    baseCents: 72_000n,
    conversionsCents: 560_00n,
    totalCents: 1_280_00n,
    payoutBatch: 'PAY-2026-05A',
  },
  {
    knocker: 'Asha Mehta',
    initials: 'AM',
    baseCents: 66_000n,
    conversionsCents: 480_00n,
    totalCents: 1_140_00n,
    payoutBatch: 'PAY-2026-05A',
  },
];

export const CONVERSIONS = [
  {
    donor: 'Maria Santos',
    amountCents: 240_00n,
    frequency: 'monthly',
    source: 'door',
    signedAt: '2026-05-24T16:42:11Z',
    knocker: 'JD',
  },
  {
    donor: 'Jennifer López',
    amountCents: 480_00n,
    frequency: 'monthly',
    source: 'door',
    signedAt: '2026-05-24T16:38:09Z',
    knocker: 'JM',
  },
  {
    donor: 'Sophia Patel',
    amountCents: 180_00n,
    frequency: 'monthly',
    source: 'door',
    signedAt: '2026-05-24T16:22:48Z',
    knocker: 'TM',
  },
  {
    donor: 'Robert Kim',
    amountCents: 1_200_00n,
    frequency: null,
    source: 'inside_sales',
    signedAt: '2026-05-24T15:58:14Z',
    knocker: 'JD',
  },
  {
    donor: 'Aisha Williams',
    amountCents: 360_00n,
    frequency: 'monthly',
    source: 'retargeting',
    signedAt: '2026-05-24T15:42:01Z',
    knocker: '—',
  },
  {
    donor: 'David Chen',
    amountCents: 600_00n,
    frequency: 'monthly',
    source: 'door',
    signedAt: '2026-05-24T15:18:33Z',
    knocker: 'AM',
  },
  {
    donor: 'Kevin Murphy',
    amountCents: 240_00n,
    frequency: 'monthly',
    source: 'door',
    signedAt: '2026-05-24T14:52:09Z',
    knocker: 'AR',
  },
];
