/**
 * US + AU name banks for fixture seeds.
 *
 * FIXTURE — not real PII. Names are common-enough to feel plausible (US
 * Social Security card popularity lists + ABS census top names) while
 * pulling from a wide-enough pool that lists of 50+ leads/knockers don't
 * look like the same five people on repeat.
 *
 * Mixed-ethnicity intentional — door-to-door fundraising teams at
 * Pilot-Charlie scale are demographically diverse; an "all-Smith" roster
 * would read fake.
 */

import type { Rng } from './rng';

// ─────────────────────────────────────────────────────────────────────────────
// US first names — mixed across SSA top-200 + Hispanic, Black, South Asian,
// East Asian, and Middle Eastern names common in TX/AZ field rosters.
// ─────────────────────────────────────────────────────────────────────────────

export const US_FIRST_NAMES: readonly string[] = [
  // Anglo-American
  'James',
  'Michael',
  'Robert',
  'David',
  'William',
  'Joseph',
  'Thomas',
  'Charles',
  'Matthew',
  'Anthony',
  'Donald',
  'Mark',
  'Paul',
  'Steven',
  'Andrew',
  'Kenneth',
  'George',
  'Joshua',
  'Brian',
  'Edward',
  'Ronald',
  'Timothy',
  'Jason',
  'Jeffrey',
  'Ryan',
  'Jacob',
  'Gary',
  'Nicholas',
  'Eric',
  'Jonathan',
  'Stephen',
  'Larry',
  'Justin',
  'Scott',
  'Brandon',
  'Mary',
  'Patricia',
  'Jennifer',
  'Linda',
  'Elizabeth',
  'Barbara',
  'Susan',
  'Jessica',
  'Sarah',
  'Karen',
  'Lisa',
  'Nancy',
  'Betty',
  'Sandra',
  'Margaret',
  'Ashley',
  'Kimberly',
  'Emily',
  'Donna',
  'Michelle',
  'Carol',
  'Amanda',
  'Melissa',
  'Deborah',
  'Stephanie',
  'Rebecca',
  'Laura',
  'Sharon',
  'Cynthia',
  'Kathleen',
  'Amy',
  'Olivia',
  'Sophia',
  'Charlotte',
  'Ava',
  // Hispanic / Latino
  'Carlos',
  'José',
  'Luis',
  'Miguel',
  'Juan',
  'Diego',
  'Mateo',
  'Andrés',
  'Rafael',
  'Javier',
  'Eduardo',
  'Sergio',
  'Tomás',
  'Ricardo',
  'Fernando',
  'Maria',
  'Ana',
  'Sofia',
  'Isabella',
  'Camila',
  'Valentina',
  'Lucia',
  'Daniela',
  'Gabriela',
  'Carmen',
  'Adriana',
  'Rosa',
  'Cristina',
  // Black / African-American
  'Jordan',
  'Marcus',
  'Tyrone',
  'Andre',
  'Devon',
  'Malik',
  'Jamal',
  'Darius',
  'DeShawn',
  'Terrell',
  'Reggie',
  'Aaliyah',
  'Imani',
  'Jada',
  'Zaria',
  'Tiana',
  'Asia',
  'Nia',
  'Kiana',
  'Brianna',
  'Latoya',
  // South Asian
  'Aarav',
  'Vihaan',
  'Arjun',
  'Krishna',
  'Rohan',
  'Karan',
  'Nikhil',
  'Rahul',
  'Anand',
  'Kiran',
  'Priya',
  'Ananya',
  'Neha',
  'Aisha',
  'Zara',
  'Diya',
  'Kavya',
  'Riya',
  'Asha',
  'Meera',
  // East Asian
  'Kim',
  'Min',
  'Jin',
  'Sung',
  'Hiroshi',
  'Kenji',
  'Daiki',
  'Haruto',
  'Yuki',
  'Wei',
  'Jian',
  'Xiang',
  'Lin',
  'Mei',
  'Yuna',
  'Hana',
  // Middle Eastern
  'Omar',
  'Hassan',
  'Khalil',
  'Tariq',
  'Ahmad',
  'Bilal',
  'Yusuf',
  'Fatima',
  'Aisha',
  'Zainab',
  'Layla',
  'Nadia',
];

// ─────────────────────────────────────────────────────────────────────────────
// US last names — Census 2020 top-1000 sampling, mixed-ethnicity.
// ─────────────────────────────────────────────────────────────────────────────

export const US_LAST_NAMES: readonly string[] = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Perez',
  'Thompson',
  'White',
  'Harris',
  'Sanchez',
  'Clark',
  'Ramirez',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
  'Flores',
  'Green',
  'Adams',
  'Nelson',
  'Baker',
  'Hall',
  'Rivera',
  'Campbell',
  'Mitchell',
  'Carter',
  'Roberts',
  'Gomez',
  'Phillips',
  'Evans',
  'Turner',
  'Diaz',
  'Parker',
  'Cruz',
  'Edwards',
  'Collins',
  'Reyes',
  'Stewart',
  'Morris',
  'Morales',
  'Murphy',
  'Cook',
  'Rogers',
  'Gutierrez',
  'Ortiz',
  'Morgan',
  'Cooper',
  'Peterson',
  'Bailey',
  'Reed',
  'Kelly',
  'Howard',
  'Ramos',
  'Kim',
  'Cox',
  'Ward',
  'Richardson',
  'Watson',
  'Brooks',
  'Chavez',
  'Wood',
  'James',
  'Bennett',
  'Gray',
  'Mendoza',
  'Ruiz',
  'Hughes',
  'Price',
  'Alvarez',
  'Castillo',
  'Sanders',
  'Patel',
  'Myers',
  'Long',
  'Ross',
  'Foster',
  'Jimenez',
  'Powell',
  'Jenkins',
  'Perry',
  'Russell',
  'Sullivan',
  'Bell',
  'Coleman',
  'Butler',
  'Henderson',
  'Barnes',
  'Gonzales',
  'Fisher',
  'Vasquez',
  'Simmons',
  'Romero',
  'Jordan',
  'Patterson',
  'Alexander',
  'Hamilton',
  'Graham',
  'Reynolds',
  'Griffin',
  'Wallace',
  'Moreno',
  'West',
  'Cole',
  'Hayes',
  'Bryant',
  'Herrera',
  'Gibson',
  'Ellis',
  'Tran',
  'Medina',
  'Aguilar',
  'Stevens',
  'Murray',
  'Ford',
  'Castro',
  'Marshall',
  'Owens',
  'Harrison',
  'Fernandez',
  'McDonald',
  'Woods',
  'Washington',
  'Kennedy',
  'Wells',
  'Vargas',
  'Henry',
  'Chen',
  'Freeman',
  'Webb',
  'Tucker',
  'Guzman',
  'Burns',
  'Crawford',
  'Olson',
  'Simpson',
  'Porter',
  'Hunter',
  'Gordon',
  'Mendez',
  'Silva',
  'Shaw',
  'Snyder',
  'Mason',
  'Dixon',
  'Hunt',
  'Munoz',
  'Hicks',
  'Holmes',
  'Palmer',
  'Wagner',
  'Black',
  'Robertson',
  'Boyd',
  'Rose',
  'Stone',
  'Salazar',
  'Fox',
  'Warren',
  'Mills',
  'Meyer',
  'Rice',
  'Schmidt',
  'Garza',
  'Daniels',
  'Ferguson',
  'Nichols',
  'Stephens',
  'Soto',
  'Weaver',
  'Ryan',
  'Gardner',
  'Payne',
  'Grant',
  'Dunn',
  'Kelley',
  'Spencer',
  'Hawkins',
  'Arnold',
  'Pierce',
  'Vazquez',
  'Hansen',
  'Peters',
  'Santos',
  'Hart',
  'Bradley',
  'Knight',
  'Elliott',
  'Cunningham',
  'Duncan',
  'Armstrong',
  'Hudson',
  'Carroll',
  'Lane',
  'Riley',
  'Andrews',
  'Alvarado',
  'Ray',
  'Delgado',
  'Berry',
  'Perkins',
  'Hoffman',
  'Johnston',
  'Matthews',
  'Pena',
  'Richards',
  'Contreras',
  'Willis',
  'Carpenter',
  'Lawrence',
  'Sandoval',
  'Guerrero',
  'George',
  'Chapman',
  'Rios',
  'Estrada',
  'Ortega',
  'Watkins',
  'Greene',
  'Nunez',
  'Wheeler',
  'Valdez',
  'Harper',
  'Burke',
  'Larson',
  'Santiago',
  'Maldonado',
  'Morrison',
  'Franklin',
  'Carlson',
  'Austin',
  'Dominguez',
  'Carr',
  'Lawson',
  'Jacobs',
  'Obrien',
  'Lynch',
  'Singh',
  'Vega',
];

// ─────────────────────────────────────────────────────────────────────────────
// AU first names — ABS top names sampling + multicultural Sydney/Melbourne
// ─────────────────────────────────────────────────────────────────────────────

export const AU_FIRST_NAMES: readonly string[] = [
  // Anglo-Australian
  'Oliver',
  'William',
  'Jack',
  'Noah',
  'Thomas',
  'James',
  'Lucas',
  'Liam',
  'Harrison',
  'Henry',
  'Ethan',
  'Cooper',
  'Hudson',
  'Mason',
  'Leo',
  'Hugo',
  'Archie',
  'Charlie',
  'Max',
  'Alexander',
  'Samuel',
  'Benjamin',
  'Levi',
  'Patrick',
  'Riley',
  'Sebastian',
  'Daniel',
  'Edward',
  'Eli',
  'George',
  'Olivia',
  'Charlotte',
  'Mia',
  'Amelia',
  'Isla',
  'Ava',
  'Grace',
  'Sophie',
  'Chloe',
  'Lily',
  'Sophia',
  'Zoe',
  'Harper',
  'Evie',
  'Matilda',
  'Ella',
  'Ruby',
  'Willow',
  'Maya',
  'Aria',
  'Ivy',
  'Layla',
  'Audrey',
  'Hazel',
  'Emily',
  'Indi',
  'Frankie',
  'Sienna',
  'Pippa',
  'Eloise',
  // Greek / Italian / Lebanese / Maltese (Sydney/Melbourne staples)
  'Dimitri',
  'Stavros',
  'Nikolas',
  'Yianni',
  'Andreas',
  'Giancarlo',
  'Luca',
  'Marco',
  'Matteo',
  'Giuseppe',
  'Antonio',
  'Salvatore',
  'Vincenzo',
  'Sophia',
  'Sofia',
  'Bianca',
  'Gianna',
  'Maria',
  'Anna',
  // Vietnamese / Chinese / Korean (top AU migrant cohorts)
  'An',
  'Binh',
  'Duy',
  'Hai',
  'Khoa',
  'Linh',
  'Nam',
  'Tu',
  'Wei',
  'Jian',
  'Yi',
  'Hao',
  'Ming',
  'Hua',
  'Mei',
  'Lin',
  'Min',
  'Joon',
  'Hyun',
  'Soo',
  'Yu',
  'Ji',
  'Eun',
  'Sun',
  // South Asian (Indian migrant communities)
  'Aarav',
  'Krishna',
  'Arjun',
  'Rohan',
  'Rahul',
  'Karan',
  'Priya',
  'Aisha',
  'Neha',
  'Kavya',
  'Anika',
  'Diya',
  // Middle Eastern (Sydney's western suburbs)
  'Omar',
  'Khalil',
  'Hassan',
  'Bilal',
  'Tariq',
  'Yusuf',
  'Fatima',
  'Layla',
  'Nadia',
  'Zainab',
  // Indigenous Australian (Aboriginal/Torres Strait Islander names — used
  // sparingly; for sponsor-update copy we lean on multicultural Sydney mix)
  'Jarrah',
  'Kira',
  'Marlee',
  'Tyson',
];

export const AU_LAST_NAMES: readonly string[] = [
  // Anglo
  'Smith',
  'Jones',
  'Williams',
  'Brown',
  'Wilson',
  'Taylor',
  'Johnson',
  'White',
  'Martin',
  'Anderson',
  'Thompson',
  'Nguyen',
  'Thomas',
  'Walker',
  'Harris',
  'Lee',
  'Ryan',
  'Robinson',
  'Kelly',
  'King',
  'Wright',
  'Clarke',
  'Stewart',
  'Hall',
  'Green',
  'Wood',
  'Mitchell',
  'Campbell',
  'Roberts',
  'Edwards',
  'Hill',
  'Cox',
  'Bell',
  'Cooper',
  'Ward',
  'Murphy',
  'Watson',
  'Bailey',
  'Cook',
  'Morris',
  'Adams',
  'Carter',
  'Phillips',
  'Evans',
  'Collins',
  'Mason',
  'Foster',
  'Hughes',
  'Allen',
  'Davies',
  'Patel',
  'Singh',
  'Carroll',
  'Walsh',
  'Connor',
  'OBrien',
  'Sullivan',
  // Italian / Greek / Lebanese
  'Russo',
  'Costa',
  'Romano',
  'Esposito',
  'Bruno',
  'Bianchi',
  'Rossi',
  'Greco',
  'Marino',
  'Conti',
  'Vella',
  'Borg',
  'Magri',
  'Said',
  'Hanna',
  'Khoury',
  'Mansour',
  'Saade',
  'Habib',
  'Karam',
  'Papadopoulos',
  'Kontoleon',
  'Karras',
  'Christou',
  'Pappas',
  // Vietnamese / Chinese / Korean
  'Nguyen',
  'Tran',
  'Le',
  'Pham',
  'Hoang',
  'Vu',
  'Phan',
  'Truong',
  'Chen',
  'Wang',
  'Li',
  'Liu',
  'Lin',
  'Zhang',
  'Yang',
  'Huang',
  'Kim',
  'Park',
  'Choi',
  'Jung',
  'Kang',
  'Cho',
  // South Asian
  'Patel',
  'Sharma',
  'Singh',
  'Kumar',
  'Gupta',
  'Shah',
  'Verma',
  'Khan',
  'Ali',
  'Hussain',
  'Mahmood',
  'Rahman',
];

// ─────────────────────────────────────────────────────────────────────────────
// Internal staff (BDR / inside-sales / CSM) — initials read like "real
// employees" not "John from the demo". Mostly anglo, mixed gender, two-letter
// initials work in the existing UI.
// ─────────────────────────────────────────────────────────────────────────────

export const STAFF_NAMES: readonly { initials: string; name: string }[] = [
  { initials: 'BC', name: 'Brodie Connors' },
  { initials: 'SH', name: 'Sarah Hammond' },
  { initials: 'JD', name: 'Jordan Diaz' },
  { initials: 'AM', name: 'Asha Mehta' },
  { initials: 'TM', name: 'Tomás Mendez' },
  { initials: 'KP', name: 'Kim Park' },
  { initials: 'RV', name: 'Riley Vargas' },
  { initials: 'EB', name: 'Eli Bautista' },
  { initials: 'CS', name: 'Cameron Singh' },
  { initials: 'BR', name: 'Bianca Romano' },
  { initials: 'DQ', name: 'Dion Quintero' },
  { initials: 'AS', name: 'Aurelia Sokolov' },
  { initials: 'MC', name: 'Maya Castellanos' },
  { initials: 'IW', name: 'Imani Walker' },
  { initials: 'JB', name: 'Jacob Bell' },
  { initials: 'SW', name: 'Sage Whitfield' },
];

/**
 * Build `count` unique-by-initials fixture names from the supplied banks. We
 * round-robin first/last to avoid generating "Maria Maria" or "Smith Smith"
 * and dedupe on the two-letter initial so the avatar column stays unique.
 */
export function buildNamePool(
  rng: Rng,
  count: number,
  region: 'US' | 'AU',
): { initials: string; name: string }[] {
  const firsts = region === 'AU' ? AU_FIRST_NAMES : US_FIRST_NAMES;
  const lasts = region === 'AU' ? AU_LAST_NAMES : US_LAST_NAMES;
  const out: { initials: string; name: string }[] = [];
  const seen = new Set<string>();
  // Up to count * 5 attempts so we don't loop forever if the bank is tight.
  for (let i = 0; out.length < count && i < count * 5; i++) {
    const first = rng.pick(firsts);
    const last = rng.pick(lasts);
    const initials = (first[0]! + last[0]!).toUpperCase();
    if (seen.has(initials)) continue;
    seen.add(initials);
    out.push({ initials, name: `${first} ${last}` });
  }
  // If we exhaust the bank (unlikely until count > 400), tolerate dup
  // initials so the list reaches the target size.
  while (out.length < count) {
    const first = rng.pick(firsts);
    const last = rng.pick(lasts);
    out.push({ initials: (first[0]! + last[0]!).toUpperCase(), name: `${first} ${last}` });
  }
  return out;
}
