/**
 * Per-account fleet + zone fixtures for live satellite maps.
 *
 * Each sub-account gets a scoped slice of FleetRep + AiZone data, with its
 * own map center/zoom appropriate to where the business operates. Counts are
 * sized for legibility on the map (12 max per account), not 1:1 with the real
 * rosters in `accounts.ts`.
 */

import type { FleetRep, AiZone } from './fleet-reps';
import type { AiZoneSuggestion, AnomalyItem, ActivityEvent } from '@/components/field-ops/types';

export interface AccountFleetData {
  /** [lat, lng] for initial map center */
  center: [number, number];
  zoom: number;
  reps: FleetRep[];
  zones: AiZone[];
  /** Display label for the floating "Live · …" badge */
  scopeLabel: string;
  /** Rich field-ops panel data — AI next zones */
  aiSuggestions: AiZoneSuggestion[];
  /** Rich field-ops panel data — anomalies */
  anomalies: AnomalyItem[];
  /** Rich field-ops panel data — live activity feed */
  activity: ActivityEvent[];
}

export const ACCOUNT_FLEET: Record<string, AccountFleetData> = {
  // ─────────────────────────────────────────────────────────────────────────
  // Hope Forward · US charity · 12 reps across Texas
  // ─────────────────────────────────────────────────────────────────────────
  'hope-forward': {
    center: [31.2, -97.0],
    zoom: 6,
    scopeLabel: 'Hope Forward · US',
    reps: [
      // Austin cluster (30.27, -97.74) — 4 reps
      {
        id: 'hf1',
        initials: 'JM',
        name: 'Jordan Mosley',
        account: 'Hope Forward',
        lat: 30.2672,
        lng: -97.7431,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 12m',
        knocksToday: 84,
        conversionsToday: 31,
        lastKnockMin: 3,
        territory: 'Austin East',
      },
      {
        id: 'hf2',
        initials: 'JD',
        name: 'Jada Davis',
        account: 'Hope Forward',
        lat: 30.2515,
        lng: -97.7186,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 08m',
        knocksToday: 91,
        conversionsToday: 22,
        lastKnockMin: 1,
        territory: 'Austin Central',
      },
      {
        id: 'hf3',
        initials: 'AR',
        name: 'Aaliyah Reed',
        account: 'Hope Forward',
        lat: 30.2898,
        lng: -97.7589,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 15m',
        knocksToday: 78,
        conversionsToday: 18,
        lastKnockMin: 7,
        territory: 'Austin North',
      },
      {
        id: 'hf4',
        initials: 'TM',
        name: 'Tomás Mendez',
        account: 'Hope Forward',
        lat: 30.2451,
        lng: -97.7299,
        status: 'break',
        shiftStart: '09:00',
        hoursToday: '3h 45m · LUNCH',
        knocksToday: 64,
        conversionsToday: 14,
        lastKnockMin: 28,
        territory: 'Austin South',
      },

      // Dallas / Plano cluster (32.78, -96.80) — 4 reps
      {
        id: 'hf5',
        initials: 'AM',
        name: 'Asha Mehta',
        account: 'Hope Forward',
        lat: 32.7821,
        lng: -96.8005,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 42m',
        knocksToday: 66,
        conversionsToday: 12,
        lastKnockMin: 5,
        territory: 'Dallas Metro',
      },
      {
        id: 'hf6',
        initials: 'CS',
        name: 'Cameron Singh',
        account: 'Hope Forward',
        lat: 32.7901,
        lng: -96.8214,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 30m',
        knocksToday: 58,
        conversionsToday: 11,
        lastKnockMin: 4,
        territory: 'Dallas North',
      },
      {
        id: 'hf7',
        initials: 'RV',
        name: 'Riley Vargas',
        account: 'Hope Forward',
        lat: 33.0198,
        lng: -96.6989,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 22m',
        knocksToday: 49,
        conversionsToday: 9,
        lastKnockMin: 6,
        territory: 'Plano',
      },
      {
        id: 'hf8',
        initials: 'EB',
        name: 'Eli Bautista',
        account: 'Hope Forward',
        lat: 33.0044,
        lng: -96.7186,
        status: 'idle',
        shiftStart: '09:30',
        hoursToday: '3h 50m',
        knocksToday: 41,
        conversionsToday: 6,
        lastKnockMin: 22,
        territory: 'Plano',
      },

      // Houston cluster (29.76, -95.37) — 4 reps
      {
        id: 'hf9',
        initials: 'KP',
        name: 'Kim Park',
        account: 'Hope Forward',
        lat: 29.7589,
        lng: -95.3676,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 05m',
        knocksToday: 71,
        conversionsToday: 15,
        lastKnockMin: 4,
        territory: 'Houston Central',
      },
      {
        id: 'hf10',
        initials: 'DR',
        name: 'Devon Russell',
        account: 'Hope Forward',
        lat: 29.7434,
        lng: -95.3512,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 11m',
        knocksToday: 58,
        conversionsToday: 11,
        lastKnockMin: 2,
        territory: 'Houston SE',
      },
      {
        id: 'hf11',
        initials: 'ML',
        name: 'Marcus Lee',
        account: 'Hope Forward',
        lat: 29.7782,
        lng: -95.3951,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 00m',
        knocksToday: 62,
        conversionsToday: 13,
        lastKnockMin: 3,
        territory: 'Houston West',
      },
      {
        id: 'hf12',
        initials: 'NK',
        name: 'Naomi Kowalski',
        account: 'Hope Forward',
        lat: 29.7218,
        lng: -95.4012,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Houston West',
      },
    ],
    zones: [
      {
        lat: 30.2415,
        lng: -97.7689,
        label: 'Austin South · 78704',
        reason: 'Propensity 0.81 · ACS median income $94k · 14% conv (lookalike)',
      },
      {
        lat: 33.0198,
        lng: -96.6989,
        label: 'Plano · 75024',
        reason: 'Propensity 0.78 · lookalike to Highland Park (top cohort)',
      },
      {
        lat: 29.6197,
        lng: -95.6349,
        label: 'Sugar Land · 77479',
        reason: 'Propensity 0.74 · low cannibalisation w/ Houston SE',
      },
    ],
    aiSuggestions: [
      {
        id: 'hf-zone-1',
        name: 'Austin South · 78704',
        propensity: 0.81,
        reasonOneLiner: 'ACS median income $94k · charity-giving propensity 0.83 · 0% saturation',
        estLiftPp: 14,
        saturationPercent: 0,
        recommendedReps: 2,
      },
      {
        id: 'hf-zone-2',
        name: 'Plano · 75024',
        propensity: 0.78,
        reasonOneLiner: 'Lookalike to top-performing Highland Park · low Dallas saturation',
        estLiftPp: 11,
        saturationPercent: 12,
        recommendedReps: 2,
      },
      {
        id: 'hf-zone-3',
        name: 'Sugar Land · 77479',
        propensity: 0.74,
        reasonOneLiner: '24% knocks-not-converted in nearby Bellaire = warm re-engage pool',
        estLiftPp: 9,
        saturationPercent: 8,
        recommendedReps: 1,
      },
    ],
    anomalies: [
      {
        id: 'hf-anom-1',
        severity: 'critical',
        title: 'Devon R offline since 09:00',
        detail: 'Houston SE shift uncovered. Auto-SMS + push sent. Backup: reassign to Marcus L.',
        actionLabel: 'Reassign',
      },
      {
        id: 'hf-anom-2',
        severity: 'warn',
        title: 'Tomás M lunch break > 45min',
        detail: 'On break since 12:48. Auto-reminder push sent.',
        actionLabel: 'Nudge',
      },
      {
        id: 'hf-anom-3',
        severity: 'warn',
        title: 'Eli B conv. rate dropped 11pp',
        detail: 'Last 4 hours vs trailing avg. Try script v3.2 + check Plano saturation.',
        actionLabel: 'Open 1:1',
      },
    ],
    activity: [
      {
        id: 'hf-act-1',
        at: '14:42',
        actorInitials: 'JD',
        type: 'conversion',
        primary: 'Conversion captured',
        secondary: 'Maria Santos · $24/mo recurring · Austin East',
      },
      {
        id: 'hf-act-2',
        at: '14:41',
        actorInitials: 'JM',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '4218 Lakeview Dr, Austin TX',
      },
      {
        id: 'hf-act-3',
        at: '14:40',
        actorInitials: 'KP',
        type: 'callback_scheduled',
        primary: 'Callback scheduled',
        secondary: 'Robert Kim · Tue 3pm · Houston Central',
      },
      {
        id: 'hf-act-4',
        at: '14:38',
        actorInitials: 'AR',
        type: 'shift_start',
        primary: 'Started shift',
        secondary: 'Austin North · 8h shift',
      },
      {
        id: 'hf-act-5',
        at: '14:36',
        actorInitials: 'AM',
        type: 'conversion',
        primary: 'Conversion captured',
        secondary: 'James Whitfield · $36/mo · Dallas Metro',
      },
      {
        id: 'hf-act-6',
        at: '14:35',
        actorInitials: 'TM',
        type: 'shift_break_return',
        primary: 'Returned from break',
        secondary: 'Lunch 45m · Austin South',
      },
      {
        id: 'hf-act-7',
        at: '14:32',
        actorInitials: 'ML',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '1502 Cedar St, Houston · $48/mo recurring',
      },
      {
        id: 'hf-act-8',
        at: '14:30',
        actorInitials: 'JM',
        type: 'knock_not_home',
        primary: 'Knock recorded · NOT HOME',
        secondary: '4216 Lakeview Dr, Austin TX',
      },
      {
        id: 'hf-act-9',
        at: '14:28',
        actorInitials: 'CS',
        type: 'conversion',
        primary: 'Conversion captured',
        secondary: 'Patricia Adler · $30/mo · Dallas North',
      },
      {
        id: 'hf-act-10',
        at: '14:25',
        actorInitials: 'RV',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '6004 Legacy Dr, Plano TX',
      },
      {
        id: 'hf-act-11',
        at: '14:22',
        actorInitials: 'JD',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '2210 Manor Rd, Austin · $20/mo recurring',
      },
      {
        id: 'hf-act-12',
        at: '14:18',
        actorInitials: 'DR',
        type: 'shift_break_start',
        primary: 'Started break',
        secondary: 'Lunch · Houston SE',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // World Vision · AU charity · 12 reps across Syd/Mel/Bne
  // ─────────────────────────────────────────────────────────────────────────
  'world-vision': {
    center: [-32.5, 148.0],
    zoom: 5,
    scopeLabel: 'World Vision AU',
    reps: [
      // Sydney cluster (-33.87, 151.21) — 4 reps
      {
        id: 'wv1',
        initials: 'AC',
        name: 'Amelia Chen',
        account: 'World Vision',
        lat: -33.8688,
        lng: 151.2093,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 45m',
        knocksToday: 72,
        conversionsToday: 21,
        lastKnockMin: 2,
        territory: 'Sydney CBD',
      },
      {
        id: 'wv2',
        initials: 'LO',
        name: 'Liam O’Brien',
        account: 'World Vision',
        lat: -33.8915,
        lng: 151.1875,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 38m',
        knocksToday: 65,
        conversionsToday: 14,
        lastKnockMin: 5,
        territory: 'Sydney Inner West',
      },
      {
        id: 'wv3',
        initials: 'ZH',
        name: 'Zara Habib',
        account: 'World Vision',
        lat: -33.8434,
        lng: 151.2541,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 51m',
        knocksToday: 58,
        conversionsToday: 12,
        lastKnockMin: 1,
        territory: 'Sydney East',
      },
      {
        id: 'wv4',
        initials: 'JW',
        name: 'Jack Williams',
        account: 'World Vision',
        lat: -33.9173,
        lng: 151.2354,
        status: 'break',
        shiftStart: '10:00',
        hoursToday: '3h 20m · LUNCH',
        knocksToday: 41,
        conversionsToday: 7,
        lastKnockMin: 35,
        territory: 'Sydney South',
      },

      // Melbourne cluster (-37.81, 144.96) — 4 reps
      {
        id: 'wv5',
        initials: 'IN',
        name: 'Isabel Nguyen',
        account: 'World Vision',
        lat: -37.8136,
        lng: 144.9631,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 12m',
        knocksToday: 78,
        conversionsToday: 18,
        lastKnockMin: 3,
        territory: 'Melbourne CBD',
      },
      {
        id: 'wv6',
        initials: 'HK',
        name: 'Harvey Kapoor',
        account: 'World Vision',
        lat: -37.7989,
        lng: 144.9412,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 05m',
        knocksToday: 81,
        conversionsToday: 22,
        lastKnockMin: 1,
        territory: 'Melbourne North',
      },
      {
        id: 'wv7',
        initials: 'GO',
        name: 'Grace O’Sullivan',
        account: 'World Vision',
        lat: -37.8425,
        lng: 145.0033,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 18m',
        knocksToday: 69,
        conversionsToday: 15,
        lastKnockMin: 4,
        territory: 'Melbourne East',
      },
      {
        id: 'wv8',
        initials: 'NR',
        name: 'Noah Ricci',
        account: 'World Vision',
        lat: -37.8312,
        lng: 144.9215,
        status: 'idle',
        shiftStart: '09:30',
        hoursToday: '4h 30m',
        knocksToday: 47,
        conversionsToday: 6,
        lastKnockMin: 19,
        territory: 'Melbourne West',
      },

      // Brisbane cluster (-27.47, 153.03) — 4 reps
      {
        id: 'wv9',
        initials: 'EM',
        name: 'Ethan Morrison',
        account: 'World Vision',
        lat: -27.4698,
        lng: 153.0251,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '5h 02m',
        knocksToday: 88,
        conversionsToday: 24,
        lastKnockMin: 2,
        territory: 'Brisbane CBD',
      },
      {
        id: 'wv10',
        initials: 'AS',
        name: 'Ava Singh',
        account: 'World Vision',
        lat: -27.4485,
        lng: 153.0398,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '4h 58m',
        knocksToday: 74,
        conversionsToday: 17,
        lastKnockMin: 6,
        territory: 'Brisbane North',
      },
      {
        id: 'wv11',
        initials: 'MT',
        name: 'Mia Tan',
        account: 'World Vision',
        lat: -27.4901,
        lng: 153.0089,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '5h 10m',
        knocksToday: 61,
        conversionsToday: 13,
        lastKnockMin: 4,
        territory: 'Brisbane South',
      },
      {
        id: 'wv12',
        initials: 'BC',
        name: 'Ben Castro',
        account: 'World Vision',
        lat: -27.4612,
        lng: 153.0512,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Brisbane East',
      },
    ],
    zones: [
      {
        lat: -33.8174,
        lng: 151.0023,
        label: 'Parramatta · 2150',
        reason: 'Propensity 0.79 · SEIFA decile 9 · large multicultural cohort',
      },
      {
        lat: -37.7693,
        lng: 144.9844,
        label: 'Brunswick · 3056',
        reason: 'Propensity 0.82 · charity supporter density top quintile',
      },
      {
        lat: -27.4015,
        lng: 153.1198,
        label: 'Chermside · 4032',
        reason: 'Propensity 0.76 · CoreLogic AU growth corridor · low saturation',
      },
    ],
    aiSuggestions: [
      {
        id: 'wv-zone-1',
        name: 'Parramatta · 2150',
        propensity: 0.79,
        reasonOneLiner:
          'SEIFA decile 9 · large multicultural cohort · child sponsorship affinity 0.84',
        estLiftPp: 13,
        saturationPercent: 4,
        recommendedReps: 2,
      },
      {
        id: 'wv-zone-2',
        name: 'Brunswick · 3056',
        propensity: 0.82,
        reasonOneLiner: 'Charity supporter density top quintile · prior campaign uplift 17pp',
        estLiftPp: 15,
        saturationPercent: 6,
        recommendedReps: 2,
      },
      {
        id: 'wv-zone-3',
        name: 'Chermside · 4032',
        propensity: 0.76,
        reasonOneLiner:
          'CoreLogic AU growth corridor · low Brisbane saturation · 11k door catchment',
        estLiftPp: 10,
        saturationPercent: 3,
        recommendedReps: 1,
      },
    ],
    anomalies: [
      {
        id: 'wv-anom-1',
        severity: 'critical',
        title: 'Liam P offline since 09:30',
        detail:
          'Sydney North shift uncovered. Auto-SMS sent. Backup: reassign to Ava T (Brisbane North).',
        actionLabel: 'Reassign',
      },
      {
        id: 'wv-anom-2',
        severity: 'warn',
        title: 'Mia S lunch break > 50min',
        detail: 'On break since 12:45 AEST. Auto-reminder push sent to iPad.',
        actionLabel: 'Nudge',
      },
      {
        id: 'wv-anom-3',
        severity: 'warn',
        title: 'Oliver K conv. rate dropped 9pp',
        detail:
          'Last 4 hours vs trailing avg. Try sponsorship script v4.1 + check Melbourne West saturation.',
        actionLabel: 'Open 1:1',
      },
    ],
    activity: [
      {
        id: 'wv-act-1',
        at: '14:42',
        actorInitials: 'AC',
        type: 'conversion',
        primary: 'Child sponsorship captured',
        secondary: 'Sarah Mitchell · A$50/mo · Sydney CBD',
      },
      {
        id: 'wv-act-2',
        at: '14:40',
        actorInitials: 'EM',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '142 Adelaide St, Brisbane CBD',
      },
      {
        id: 'wv-act-3',
        at: '14:38',
        actorInitials: 'IN',
        type: 'conversion',
        primary: 'Child sponsorship captured',
        secondary: 'Daniel Tran · A$45/mo · Melbourne CBD',
      },
      {
        id: 'wv-act-4',
        at: '14:36',
        actorInitials: 'ZH',
        type: 'callback_scheduled',
        primary: 'Callback scheduled',
        secondary: 'Priya Sharma · Thu 6pm · Sydney East',
      },
      {
        id: 'wv-act-5',
        at: '14:33',
        actorInitials: 'HK',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '88 Sydney Rd, Brunswick · A$60/mo recurring',
      },
      {
        id: 'wv-act-6',
        at: '14:30',
        actorInitials: 'JW',
        type: 'shift_break_return',
        primary: 'Returned from break',
        secondary: 'Lunch 50m · Sydney South',
      },
      {
        id: 'wv-act-7',
        at: '14:27',
        actorInitials: 'GO',
        type: 'conversion',
        primary: 'Child sponsorship captured',
        secondary: 'Aroha Wilson · A$50/mo · Melbourne East',
      },
      {
        id: 'wv-act-8',
        at: '14:24',
        actorInitials: 'AS',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '14 Hamilton Rd, Chermside',
      },
      {
        id: 'wv-act-9',
        at: '14:22',
        actorInitials: 'NR',
        type: 'knock_not_home',
        primary: 'Knock recorded · NOT HOME',
        secondary: '212 Barkly St, Footscray',
      },
      {
        id: 'wv-act-10',
        at: '14:18',
        actorInitials: 'MT',
        type: 'conversion',
        primary: 'Child sponsorship captured',
        secondary: 'Jamal Chen · A$40/mo · Brisbane South',
      },
      {
        id: 'wv-act-11',
        at: '14:15',
        actorInitials: 'EM',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '67 Wickham Tce, Brisbane · A$75/mo · 2 children',
      },
      {
        id: 'wv-act-12',
        at: '14:10',
        actorInitials: 'LO',
        type: 'shift_break_start',
        primary: 'Started break',
        secondary: 'Lunch · Sydney Inner West',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PestMax · US commercial · 8 reps Dallas / Phoenix / Houston
  // ─────────────────────────────────────────────────────────────────────────
  pestmax: {
    center: [32.0, -103.0],
    zoom: 5,
    scopeLabel: 'PestMax · US',
    reps: [
      // Dallas cluster (32.78, -96.80) — 4 reps
      {
        id: 'pm1',
        initials: 'BC',
        name: 'Bianca Costa',
        account: 'PestMax',
        lat: 32.7767,
        lng: -96.797,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 12m',
        knocksToday: 38,
        conversionsToday: 9,
        lastKnockMin: 12,
        territory: 'Dallas Metro',
      },
      {
        id: 'pm2',
        initials: 'HK',
        name: 'Hiroshi Kato',
        account: 'PestMax',
        lat: 32.7712,
        lng: -96.7826,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 18m',
        knocksToday: 42,
        conversionsToday: 7,
        lastKnockMin: 5,
        territory: 'Dallas North',
      },
      {
        id: 'pm3',
        initials: 'RG',
        name: 'Rafael Gomez',
        account: 'PestMax',
        lat: 32.7895,
        lng: -96.8054,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 02m',
        knocksToday: 51,
        conversionsToday: 11,
        lastKnockMin: 8,
        territory: 'Dallas South',
      },
      {
        id: 'pm4',
        initials: 'SK',
        name: 'Sara Kowalski',
        account: 'PestMax',
        lat: 32.7654,
        lng: -96.8125,
        status: 'break',
        shiftStart: '08:00',
        hoursToday: '4h 45m · LUNCH',
        knocksToday: 29,
        conversionsToday: 4,
        lastKnockMin: 32,
        territory: 'Dallas Metro',
      },

      // Phoenix cluster (33.45, -112.07) — 2 reps
      {
        id: 'pm5',
        initials: 'TN',
        name: 'Tara Nguyen',
        account: 'PestMax',
        lat: 33.4484,
        lng: -112.074,
        status: 'active',
        shiftStart: '07:30',
        hoursToday: '5h 50m',
        knocksToday: 45,
        conversionsToday: 8,
        lastKnockMin: 3,
        territory: 'Phoenix Metro',
      },
      {
        id: 'pm6',
        initials: 'JL',
        name: 'José Luna',
        account: 'PestMax',
        lat: 33.4625,
        lng: -112.0891,
        status: 'idle',
        shiftStart: '07:30',
        hoursToday: '6h 02m',
        knocksToday: 33,
        conversionsToday: 4,
        lastKnockMin: 24,
        territory: 'Phoenix West',
      },

      // Houston cluster (29.76, -95.37) — 2 reps
      {
        id: 'pm7',
        initials: 'AT',
        name: 'Aiden Thomas',
        account: 'PestMax',
        lat: 29.7604,
        lng: -95.3698,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 08m',
        knocksToday: 48,
        conversionsToday: 9,
        lastKnockMin: 6,
        territory: 'Houston SE',
      },
      {
        id: 'pm8',
        initials: 'DG',
        name: 'Diana Gallagher',
        account: 'PestMax',
        lat: 29.7515,
        lng: -95.3812,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Houston SE',
      },
    ],
    zones: [
      {
        lat: 32.8136,
        lng: -96.6483,
        label: 'Garland · 75040',
        reason: 'Propensity 0.71 · termite hotspot · high SFR density',
      },
      {
        lat: 33.4942,
        lng: -111.926,
        label: 'Scottsdale · 85251',
        reason: 'Propensity 0.74 · premium service tier · low cannibalisation',
      },
    ],
    aiSuggestions: [
      {
        id: 'pm-zone-1',
        name: 'Garland · 75040',
        propensity: 0.71,
        reasonOneLiner: 'Termite hotspot · high SFR density · 38% commercial property mix',
        estLiftPp: 10,
        saturationPercent: 5,
        recommendedReps: 2,
      },
      {
        id: 'pm-zone-2',
        name: 'Scottsdale · 85254',
        propensity: 0.74,
        reasonOneLiner: 'Premium service tier · low Phoenix cannibalisation · HOA-permitted',
        estLiftPp: 12,
        saturationPercent: 7,
        recommendedReps: 2,
      },
      {
        id: 'pm-zone-3',
        name: 'Cypress · 77433',
        propensity: 0.69,
        reasonOneLiner: 'New-build subdivision · termite scope · Houston West expansion play',
        estLiftPp: 8,
        saturationPercent: 2,
        recommendedReps: 1,
      },
    ],
    anomalies: [
      {
        id: 'pm-anom-1',
        severity: 'critical',
        title: 'Aiden T no completed calls in 2hr',
        detail: 'Houston SE route. Possible vehicle issue or no-knock zone — check in via call.',
        actionLabel: 'Call rep',
      },
      {
        id: 'pm-anom-2',
        severity: 'warn',
        title: 'Sara K lunch > 60min',
        detail: 'On break since 12:15 CT. Auto-reminder push sent.',
        actionLabel: 'Nudge',
      },
      {
        id: 'pm-anom-3',
        severity: 'warn',
        title: 'Installer no-show on 3 pending appts',
        detail:
          'Dallas Metro install crew offline. Reassign install slots before customer SLA breach.',
        actionLabel: 'Reassign installs',
      },
    ],
    activity: [
      {
        id: 'pm-act-1',
        at: '14:42',
        actorInitials: 'BC',
        type: 'conversion',
        primary: 'Service contract closed',
        secondary: 'Henderson Properties · $89/mo · 1yr · Dallas Metro',
      },
      {
        id: 'pm-act-2',
        at: '14:40',
        actorInitials: 'RG',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '4502 Lemmon Ave, Dallas',
      },
      {
        id: 'pm-act-3',
        at: '14:38',
        actorInitials: 'HK',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '2210 McKinney Ave · termite scope · $1,240',
      },
      {
        id: 'pm-act-4',
        at: '14:35',
        actorInitials: 'TN',
        type: 'conversion',
        primary: 'Service contract closed',
        secondary: 'Camelback Plaza · $145/mo · commercial · Phoenix Metro',
      },
      {
        id: 'pm-act-5',
        at: '14:33',
        actorInitials: 'AT',
        type: 'callback_scheduled',
        primary: 'Callback scheduled',
        secondary: 'Northside Office Park · Wed 10am · Houston SE',
      },
      {
        id: 'pm-act-6',
        at: '14:30',
        actorInitials: 'SK',
        type: 'shift_break_start',
        primary: 'Started break',
        secondary: 'Lunch · Dallas Metro',
      },
      {
        id: 'pm-act-7',
        at: '14:27',
        actorInitials: 'JL',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '7820 W Thomas Rd, Phoenix',
      },
      {
        id: 'pm-act-8',
        at: '14:24',
        actorInitials: 'RG',
        type: 'conversion',
        primary: 'Service contract closed',
        secondary: 'Oak Lawn Dental · $69/mo · 1yr · Dallas South',
      },
      {
        id: 'pm-act-9',
        at: '14:21',
        actorInitials: 'BC',
        type: 'knock_not_home',
        primary: 'Knock recorded · NOT HOME',
        secondary: '1880 Greenville Ave, Dallas',
      },
      {
        id: 'pm-act-10',
        at: '14:18',
        actorInitials: 'AT',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '4120 Kirby Dr, Houston · $99/mo · quarterly service',
      },
      {
        id: 'pm-act-11',
        at: '14:14',
        actorInitials: 'HK',
        type: 'shift_break_return',
        primary: 'Returned from break',
        secondary: 'Lunch 40m · Dallas North',
      },
      {
        id: 'pm-act-12',
        at: '14:08',
        actorInitials: 'TN',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '6890 N Central Ave, Phoenix',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Gold Coast Hospital · AU healthcare · 8 reps on the Gold Coast
  // ─────────────────────────────────────────────────────────────────────────
  'gold-coast-hospital': {
    center: [-28.02, 153.4],
    zoom: 11,
    scopeLabel: 'Gold Coast Hospital · AU',
    reps: [
      // Surfers Paradise (-28.00, 153.43) — 2 reps
      {
        id: 'gc1',
        initials: 'CO',
        name: 'Charlotte O’Connor',
        account: 'Gold Coast Hospital',
        lat: -28.0033,
        lng: 153.4297,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 05m',
        knocksToday: 52,
        conversionsToday: 6,
        lastKnockMin: 2,
        territory: 'Surfers Paradise',
      },
      {
        id: 'gc2',
        initials: 'JK',
        name: 'James Karras',
        account: 'Gold Coast Hospital',
        lat: -28.0095,
        lng: 153.4258,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 12m',
        knocksToday: 47,
        conversionsToday: 5,
        lastKnockMin: 4,
        territory: 'Surfers Paradise',
      },

      // Broadbeach (-28.03, 153.43) — 2 reps
      {
        id: 'gc3',
        initials: 'EH',
        name: 'Ella Henderson',
        account: 'Gold Coast Hospital',
        lat: -28.029,
        lng: 153.4351,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 08m',
        knocksToday: 44,
        conversionsToday: 5,
        lastKnockMin: 6,
        territory: 'Broadbeach',
      },
      {
        id: 'gc4',
        initials: 'OP',
        name: 'Owen Park',
        account: 'Gold Coast Hospital',
        lat: -28.0354,
        lng: 153.4289,
        status: 'break',
        shiftStart: '09:00',
        hoursToday: '3h 50m · LUNCH',
        knocksToday: 31,
        conversionsToday: 3,
        lastKnockMin: 29,
        territory: 'Broadbeach',
      },

      // Burleigh Heads (-28.10, 153.45) — 1 rep
      {
        id: 'gc5',
        initials: 'MC',
        name: 'Maya Choudhury',
        account: 'Gold Coast Hospital',
        lat: -28.0995,
        lng: 153.4503,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 15m',
        knocksToday: 38,
        conversionsToday: 4,
        lastKnockMin: 3,
        territory: 'Burleigh Heads',
      },

      // Robina (-28.08, 153.39) — 2 reps
      {
        id: 'gc6',
        initials: 'SR',
        name: 'Sienna Roberts',
        account: 'Gold Coast Hospital',
        lat: -28.0815,
        lng: 153.3899,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 02m',
        knocksToday: 40,
        conversionsToday: 6,
        lastKnockMin: 5,
        territory: 'Robina',
      },
      {
        id: 'gc7',
        initials: 'LD',
        name: 'Lachlan Diaz',
        account: 'Gold Coast Hospital',
        lat: -28.0762,
        lng: 153.3954,
        status: 'idle',
        shiftStart: '09:00',
        hoursToday: '4h 22m',
        knocksToday: 25,
        conversionsToday: 2,
        lastKnockMin: 20,
        territory: 'Robina',
      },

      // Southport (-27.97, 153.40) — 1 rep
      {
        id: 'gc8',
        initials: 'PA',
        name: 'Priya Anand',
        account: 'Gold Coast Hospital',
        lat: -27.9667,
        lng: 153.4034,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Southport',
      },
    ],
    zones: [
      {
        lat: -28.0421,
        lng: 153.4019,
        label: 'Mermaid Waters · 4218',
        reason: 'Propensity 0.78 · SEIFA decile 9 · capital campaign lookalike',
      },
      {
        lat: -28.0226,
        lng: 153.3672,
        label: 'Nerang · 4211',
        reason: 'Propensity 0.71 · low saturation · family households · catchment 12k doors',
      },
    ],
    aiSuggestions: [
      {
        id: 'gc-zone-1',
        name: 'Mermaid Waters · 4218',
        propensity: 0.78,
        reasonOneLiner: 'SEIFA decile 9 · capital campaign lookalike · 4.6k doors retiree-skew',
        estLiftPp: 12,
        saturationPercent: 4,
        recommendedReps: 2,
      },
      {
        id: 'gc-zone-2',
        name: 'Nerang · 4211',
        propensity: 0.71,
        reasonOneLiner:
          'Low saturation · family households · catchment 12k doors · GP referral overlap',
        estLiftPp: 9,
        saturationPercent: 2,
        recommendedReps: 1,
      },
      {
        id: 'gc-zone-3',
        name: 'Tweed Heads · 2485',
        propensity: 0.69,
        reasonOneLiner: 'Cross-border NSW catchment · hospital service area · older demographic',
        estLiftPp: 8,
        saturationPercent: 1,
        recommendedReps: 1,
      },
    ],
    anomalies: [
      {
        id: 'gc-anom-1',
        severity: 'critical',
        title: 'Charlotte O offline since 09:15',
        detail: 'Surfers Paradise route uncovered. Auto-SMS sent. Backup: reassign to James K.',
        actionLabel: 'Reassign',
      },
      {
        id: 'gc-anom-2',
        severity: 'warn',
        title: 'Ella H lunch break > 50min',
        detail: 'On break since 12:50 AEST. Auto-reminder push sent.',
        actionLabel: 'Nudge',
      },
      {
        id: 'gc-anom-3',
        severity: 'warn',
        title: 'Lachlan D pledge rate dropped 7pp',
        detail:
          'Last 4 hours vs trailing avg. Try the new capital campaign script + check Robina saturation.',
        actionLabel: 'Open 1:1',
      },
    ],
    activity: [
      {
        id: 'gc-act-1',
        at: '14:42',
        actorInitials: 'CO',
        type: 'conversion',
        primary: 'One-off donation captured',
        secondary: 'Margaret Wells · A$200 · Surfers Paradise',
      },
      {
        id: 'gc-act-2',
        at: '14:40',
        actorInitials: 'JK',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '24 Cavill Ave, Surfers Paradise',
      },
      {
        id: 'gc-act-3',
        at: '14:38',
        actorInitials: 'EH',
        type: 'conversion',
        primary: 'Monthly pledge captured',
        secondary: 'Geoff Tan · A$35/mo · Broadbeach',
      },
      {
        id: 'gc-act-4',
        at: '14:35',
        actorInitials: 'MC',
        type: 'knock_sale',
        primary: 'Knock recorded · CAPITAL PLEDGE',
        secondary: '188 Goodwin Tce, Burleigh Heads · A$1,500 over 12mo',
      },
      {
        id: 'gc-act-5',
        at: '14:32',
        actorInitials: 'SR',
        type: 'callback_scheduled',
        primary: 'Callback scheduled',
        secondary: 'Dr Anita Rao · Fri 2pm · Robina',
      },
      {
        id: 'gc-act-6',
        at: '14:30',
        actorInitials: 'OP',
        type: 'shift_break_start',
        primary: 'Started break',
        secondary: 'Lunch · Broadbeach',
      },
      {
        id: 'gc-act-7',
        at: '14:27',
        actorInitials: 'CO',
        type: 'knock_lead',
        primary: 'Knock recorded · LEAD',
        secondary: '76 Esplanade, Surfers Paradise',
      },
      {
        id: 'gc-act-8',
        at: '14:24',
        actorInitials: 'EH',
        type: 'conversion',
        primary: 'One-off donation captured',
        secondary: 'Kelly Brennan · A$150 · Broadbeach',
      },
      {
        id: 'gc-act-9',
        at: '14:21',
        actorInitials: 'JK',
        type: 'knock_not_home',
        primary: 'Knock recorded · NOT HOME',
        secondary: '12 Hanlan St, Surfers Paradise',
      },
      {
        id: 'gc-act-10',
        at: '14:18',
        actorInitials: 'SR',
        type: 'conversion',
        primary: 'Monthly pledge captured',
        secondary: 'Hiro Yamamoto · A$50/mo · Robina',
      },
      {
        id: 'gc-act-11',
        at: '14:14',
        actorInitials: 'MC',
        type: 'knock_sale',
        primary: 'Knock recorded · SALE',
        secondary: '210 W Burleigh Rd, Burleigh Heads · A$80/mo recurring',
      },
      {
        id: 'gc-act-12',
        at: '14:08',
        actorInitials: 'LD',
        type: 'shift_break_return',
        primary: 'Returned from break',
        secondary: 'Lunch 35m · Robina',
      },
    ],
  },
};

export function getAccountFleet(slug: string): AccountFleetData | undefined {
  return ACCOUNT_FLEET[slug];
}
