/**
 * Per-account Marketing Studio registry.
 *
 * Every account that shows up at /accounts/[slug]/marketing-studio pulls
 * its 7-surface workspace data (creatives, campaigns, retargeting cohorts,
 * brand-safety rules, recent blocks, providers, pipeline counters, KPIs)
 * from this single registry. Scope is enforced by the slug lookup — no
 * cross-account leakage at the UI layer.
 *
 * Themes drive `pickCreativeImage(theme, id)` so every tile shows a
 * vertical-appropriate photo from /public/creative-bank/. The themes
 * listed on `AccountMarketing.themes` are also used as the menu of themes
 * the generator's variant-spawn cycles through for the account.
 */

import type { CreativeTheme } from './creative-images';

export type Channel = 'meta' | 'google' | 'tiktok' | 'youtube' | 'email' | 'sms';
export type Format = 'image' | 'carousel' | 'video' | 'avatar' | 'text';
export type CreativeStatus = 'draft' | 'review' | 'approved' | 'published' | 'blocked';

export interface ScopedCreative {
  id: string;
  headline: string;
  copy: string;
  theme: CreativeTheme;
  channel: Channel;
  format: Format;
  status: CreativeStatus;
  spendCents: number;
  conversions: number;
  convRate: number;
  roas: number;
  liveAt?: string; // ISO
  reviewerInitials?: string;
}

export interface ScopedCampaign {
  id: string;
  name: string;
  channel: Channel;
  status: 'active' | 'paused' | 'scheduled' | 'ended';
  budgetCents: number;
  spendCents: number;
  impressions: number;
  clicks: number;
  conversions: number;
  ctrPct: number;
  roas: number;
  attribution: 'knock' | 'inside_sales' | 'retargeting' | 'cold';
  startedAt: string;
}

export interface ScopedRetargetingCohort {
  id: string;
  name: string;
  source: string;
  audienceSize: number;
  reach: number;
  ctrPct: number;
  attributedConversions: number;
  revenueCents: number;
}

export interface ScopedBrandRule {
  id: string;
  category: 'charity' | 'pest' | 'solar' | 'energy' | 'healthcare' | 'generic';
  rule: string;
  scope: string; // e.g. "US (FTC, ACFR)" or "AU (ACNC, ACL)"
  severity: 'critical' | 'warn' | 'info';
}

export interface ScopedBlock {
  id: string;
  creativeId: string;
  creativeHeadline: string;
  ruleViolated: string;
  severity: 'critical' | 'warn' | 'info';
  reviewer: string;
  blockedAt: string;
  status: 'pending' | 'released' | 'rewritten';
}

export interface ScopedProvider {
  kind: string;
  status: 'connected' | 'sandbox' | 'not_connected' | 'error';
  accountLabel: string;
  callsToday: number;
  costCentsToday: number;
  lastPingAt: string;
}

export interface AccountMarketing {
  scopeLabel: string;
  currency: 'USD' | 'AUD' | 'SGD';
  region: 'US' | 'AU' | 'SG';
  vertical: 'charity' | 'commercial' | 'healthcare';
  /** Themes used by the generator + library scope filters. */
  themes: CreativeTheme[];
  /** Channels this account actively runs on. */
  channels: Channel[];
  creatives: ScopedCreative[];
  campaigns: ScopedCampaign[];
  retargetingCohorts: ScopedRetargetingCohort[];
  brandRules: ScopedBrandRule[];
  recentBlocks: ScopedBlock[];
  providers: ScopedProvider[];
  pipelineCounts: {
    brief: number;
    compose: number;
    variation: number;
    review: number;
    publish: number;
    measure: number;
  };
  kpis: {
    creativesThisWeek: number;
    safetyPassPct: number;
    avgCostPerCreativeCents: number;
    activeCampaigns: number;
    rollingRoas: number;
    aiAssistHoursSaved: number;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Hope Forward — US charity (recurring giving / sponsor a child / meals)
// ─────────────────────────────────────────────────────────────────────────────
const HOPE_FORWARD: AccountMarketing = {
  scopeLabel: 'Hope Forward · US',
  currency: 'USD',
  region: 'US',
  vertical: 'charity',
  themes: [
    'charity_food',
    'charity_water',
    'charity_children',
    'charity_disaster',
    'charity_medical',
  ],
  channels: ['meta', 'google', 'youtube', 'email', 'sms'],
  creatives: [
    {
      id: 'hf_cr_0001',
      headline: 'Five dollars covers a meal — every Tuesday.',
      copy: 'Hope Forward · Tx-based recurring giving · $5/wk · ACH or card · tax-deductible.',
      theme: 'charity_food',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 12_400,
      conversions: 88,
      convRate: 4.8,
      roas: 6.4,
      liveAt: '2026-05-08',
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0002',
      headline: 'Sponsor a child for $5/week. Make 2026 different.',
      copy: 'Recurring monthly · cancel anytime · 4-star Charity Navigator · 92¢ to programs.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 9_840,
      conversions: 71,
      convRate: 4.3,
      roas: 5.9,
      liveAt: '2026-05-12',
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0003',
      headline: 'Help feed 50 Texas families this month.',
      copy: 'Hope Forward · TX hunger relief · $25 covers a family for a week · tax receipt by email.',
      theme: 'charity_food',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 7_120,
      conversions: 54,
      convRate: 3.9,
      roas: 5.2,
      liveAt: '2026-05-14',
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0004',
      headline: 'Disaster relief in Houston — your gift doubles today.',
      copy: 'Hope Forward · Hurricane response · matched 2:1 by board · 100% to relief.',
      theme: 'charity_disaster',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 18_200,
      conversions: 96,
      convRate: 4.1,
      roas: 5.7,
      liveAt: '2026-05-09',
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0005',
      headline: 'Renew your faith in giving — Hope Forward, 2026.',
      copy: 'Annual giving day · 7 May 2026 · matched 2:1 by anonymous donor · ACH preferred.',
      theme: 'charity_food',
      channel: 'youtube',
      format: 'video',
      status: 'published',
      spendCents: 31_200,
      conversions: 71,
      convRate: 3.6,
      roas: 5.1,
      liveAt: '2026-05-06',
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0006',
      headline: 'A Hope Forward dollar lasts longer.',
      copy: '92¢ of every dollar to programs. Tax-deductible · EIN 47-8821334.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 8_640,
      conversions: 42,
      convRate: 3.7,
      roas: 4.8,
      liveAt: '2026-05-15',
      reviewerInitials: 'CT',
    },
    {
      id: 'hf_cr_0007',
      headline: 'Clean water for a Houston classroom · $40.',
      copy: 'Hope Forward water · one classroom = 28 kids drinking safely for a year.',
      theme: 'charity_water',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 5_320,
      conversions: 31,
      convRate: 3.4,
      roas: 4.5,
      liveAt: '2026-05-18',
    },
    {
      id: 'hf_cr_0008',
      headline: 'Our nurses thank you for your monthly gift.',
      copy: 'Hope Forward medical · mobile clinics across TX · $30/mo funds one visit.',
      theme: 'charity_medical',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 11_280,
      conversions: 48,
      convRate: 3.5,
      roas: 4.4,
      liveAt: '2026-05-11',
    },
    {
      id: 'hf_cr_0009',
      headline: "Donate a coffee, save a child's week.",
      copy: '$5 weekly recurring · ACH preferred · tax-deductible · cancel anytime in 1-click.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'image',
      status: 'review',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0010',
      headline: 'Hope Forward · TX Town Hall · join us live.',
      copy: 'Long-form leadership message · 28-min YouTube cut · sponsor drive Q3.',
      theme: 'charity_food',
      channel: 'youtube',
      format: 'video',
      status: 'published',
      spendCents: 22_800,
      conversions: 56,
      convRate: 2.9,
      roas: 3.8,
      liveAt: '2026-05-05',
    },
    {
      id: 'hf_cr_0011',
      headline: 'Disaster · Texas wildfires · we are on the ground.',
      copy: 'Hope Forward emergency · 100% to wildfire recovery · gifts processed in 2 hours.',
      theme: 'charity_disaster',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 9_640,
      conversions: 64,
      convRate: 4.4,
      roas: 5.6,
      liveAt: '2026-05-13',
    },
    {
      id: 'hf_cr_0012',
      headline: 'Sponsor a meal · $5 · every Tuesday.',
      copy: 'Tuesday Meal Match · $5 weekly · sustainer pricing · 4-star rated.',
      theme: 'charity_food',
      channel: 'sms',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0013',
      headline: 'Texas needs you · sustained giving · sign up in 2 min.',
      copy: 'Email cadence · ACH-first · 4-step sign-up · tax-deductible.',
      theme: 'charity_children',
      channel: 'email',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'hf_cr_0014',
      headline: 'A nurse, a vaccine, a child saved.',
      copy: 'Hope Forward medical · mobile vaccine clinic · $50 covers 5 vaccines.',
      theme: 'charity_medical',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 14_120,
      conversions: 58,
      convRate: 3.8,
      roas: 4.9,
      liveAt: '2026-05-10',
    },
    {
      id: 'hf_cr_0015',
      headline: 'Hope Forward · clean wells in west Texas.',
      copy: 'Water · sponsor a well for a Pecos schoolyard · $1,200 funds a year.',
      theme: 'charity_water',
      channel: 'google',
      format: 'image',
      status: 'draft',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
    },
  ],
  campaigns: [
    {
      id: 'hf_cmp_001',
      name: 'Q3 Sponsor Drive · TX-based recurring',
      channel: 'meta',
      status: 'active',
      budgetCents: 1_500_000,
      spendCents: 1_284_000,
      impressions: 1_842_300,
      clicks: 41_220,
      conversions: 818,
      ctrPct: 2.24,
      roas: 5.6,
      attribution: 'retargeting',
      startedAt: '2026-05-01',
    },
    {
      id: 'hf_cmp_002',
      name: 'Operation Cuppa · Holiday Meal Match',
      channel: 'meta',
      status: 'active',
      budgetCents: 800_000,
      spendCents: 612_000,
      impressions: 1_124_100,
      clicks: 28_120,
      conversions: 412,
      ctrPct: 2.5,
      roas: 5.2,
      attribution: 'cold',
      startedAt: '2026-05-04',
    },
    {
      id: 'hf_cmp_003',
      name: 'Texas Disaster Relief · Wildfire',
      channel: 'meta',
      status: 'active',
      budgetCents: 1_200_000,
      spendCents: 982_000,
      impressions: 1_421_800,
      clicks: 38_410,
      conversions: 612,
      ctrPct: 2.7,
      roas: 6.1,
      attribution: 'cold',
      startedAt: '2026-05-09',
    },
    {
      id: 'hf_cmp_004',
      name: 'Sustainer Upgrade · $20 → $40',
      channel: 'email',
      status: 'active',
      budgetCents: 100_000,
      spendCents: 24_000,
      impressions: 84_120,
      clicks: 12_400,
      conversions: 218,
      ctrPct: 14.7,
      roas: 8.4,
      attribution: 'inside_sales',
      startedAt: '2026-05-12',
    },
    {
      id: 'hf_cmp_005',
      name: 'Annual Giving Day · YouTube long-form',
      channel: 'youtube',
      status: 'ended',
      budgetCents: 900_000,
      spendCents: 812_000,
      impressions: 1_240_300,
      clicks: 12_812,
      conversions: 421,
      ctrPct: 1.03,
      roas: 4.9,
      attribution: 'cold',
      startedAt: '2026-04-22',
    },
    {
      id: 'hf_cmp_006',
      name: 'NOT_HOME 7d retargeting · TX zips',
      channel: 'meta',
      status: 'active',
      budgetCents: 600_000,
      spendCents: 482_000,
      impressions: 612_800,
      clicks: 18_400,
      conversions: 198,
      ctrPct: 3.0,
      roas: 4.2,
      attribution: 'retargeting',
      startedAt: '2026-05-06',
    },
    {
      id: 'hf_cmp_007',
      name: "Mother's Day re-engage · prior-year sponsors",
      channel: 'youtube',
      status: 'ended',
      budgetCents: 400_000,
      spendCents: 312_000,
      impressions: 412_800,
      clicks: 8_410,
      conversions: 124,
      ctrPct: 2.04,
      roas: 3.6,
      attribution: 'retargeting',
      startedAt: '2026-04-28',
    },
    {
      id: 'hf_cmp_008',
      name: 'Google Search · "donate to Texas families"',
      channel: 'google',
      status: 'active',
      budgetCents: 500_000,
      spendCents: 412_000,
      impressions: 184_120,
      clicks: 9_840,
      conversions: 142,
      ctrPct: 5.3,
      roas: 4.7,
      attribution: 'cold',
      startedAt: '2026-05-02',
    },
    {
      id: 'hf_cmp_009',
      name: 'SMS · monthly sustainer pulse',
      channel: 'sms',
      status: 'active',
      budgetCents: 40_000,
      spendCents: 8_400,
      impressions: 24_100,
      clicks: 3_120,
      conversions: 184,
      ctrPct: 12.9,
      roas: 11.2,
      attribution: 'knock',
      startedAt: '2026-05-15',
    },
  ],
  retargetingCohorts: [
    {
      id: 'hf_aud_001',
      name: 'Knocked / not converted · 14d',
      source: '8,422 doors · NOT_HOME + CALLBACK · TX zips',
      audienceSize: 8_422,
      reach: 142_300,
      ctrPct: 2.1,
      attributedConversions: 88,
      revenueCents: 792_000,
    },
    {
      id: 'hf_aud_002',
      name: 'Donated once · upgrade-to-monthly',
      source: 'Single-gift donors past 90d · 4,184',
      audienceSize: 4_184,
      reach: 38_220,
      ctrPct: 4.4,
      attributedConversions: 218,
      revenueCents: 1_280_000,
    },
    {
      id: 'hf_aud_003',
      name: 'Visited /sponsor · not signed',
      source: 'Site visitors 30d · /sponsor + /donate · 6,820',
      audienceSize: 6_820,
      reach: 84_120,
      ctrPct: 3.2,
      attributedConversions: 142,
      revenueCents: 624_000,
    },
    {
      id: 'hf_aud_004',
      name: 'Disaster donor · 30d lookalike',
      source: 'Hurricane donors past 30d · 1,820',
      audienceSize: 1_820,
      reach: 31_200,
      ctrPct: 2.6,
      attributedConversions: 64,
      revenueCents: 280_000,
    },
    {
      id: 'hf_aud_005',
      name: 'YouTube watcher · 75% completion',
      source: 'Watched TX Town Hall 75%+ · 12,440',
      audienceSize: 12_440,
      reach: 84_220,
      ctrPct: 1.8,
      attributedConversions: 38,
      revenueCents: 144_000,
    },
    {
      id: 'hf_aud_006',
      name: 'Sustainer dropoff · last 60d',
      source: 'Sustainer card declined past 60d · 824',
      audienceSize: 824,
      reach: 8_420,
      ctrPct: 5.4,
      attributedConversions: 124,
      revenueCents: 612_000,
    },
  ],
  brandRules: [
    {
      id: 'hf_br_001',
      category: 'charity',
      rule: 'ACFR fundraising standards · accurate cost-per-program ratio',
      scope: 'US (ACFR)',
      severity: 'critical',
    },
    {
      id: 'hf_br_002',
      category: 'charity',
      rule: 'FTC truth-in-advertising · no "guaranteed impact" claims',
      scope: 'US (FTC)',
      severity: 'critical',
    },
    {
      id: 'hf_br_003',
      category: 'charity',
      rule: 'State charitable solicitation disclosure · 29 states',
      scope: 'US (state AGs)',
      severity: 'warn',
    },
    {
      id: 'hf_br_004',
      category: 'charity',
      rule: 'Tax-deductibility disclosure · EIN + 501(c)(3) status',
      scope: 'US (IRS)',
      severity: 'warn',
    },
    {
      id: 'hf_br_005',
      category: 'charity',
      rule: 'NY State annual report boilerplate · required at footer',
      scope: 'US (NY)',
      severity: 'warn',
    },
    {
      id: 'hf_br_006',
      category: 'generic',
      rule: 'No false-scarcity language ("last chance", "expires today")',
      scope: 'US (FTC)',
      severity: 'info',
    },
  ],
  recentBlocks: [
    {
      id: 'hf_sb_001',
      creativeId: 'hf_cr_0009',
      creativeHeadline: "Donate a coffee, save a child's week.",
      ruleViolated: 'Charity US · NY · annual-report boilerplate missing',
      severity: 'info',
      reviewer: 'Auto-resolved',
      blockedAt: '2026-05-23 11:18:55',
      status: 'released',
    },
    {
      id: 'hf_sb_002',
      creativeId: 'hf_cr_0014',
      creativeHeadline: 'A nurse, a vaccine, a child saved.',
      ruleViolated: 'Charity US · ACFR · cost-per-program ratio implied',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-22 14:38:09',
      status: 'rewritten',
    },
    {
      id: 'hf_sb_003',
      creativeId: 'hf_cr_0003',
      creativeHeadline: 'Help feed 50 Texas families this month.',
      ruleViolated: 'Charity US · TX state solicitation disclosure',
      severity: 'warn',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-21 09:22:11',
      status: 'released',
    },
    {
      id: 'hf_sb_004',
      creativeId: 'hf_cr_0011',
      creativeHeadline: 'Disaster · Texas wildfires · we are on the ground.',
      ruleViolated: 'Charity US · FTC · "100% to relief" needs substantiation',
      severity: 'critical',
      reviewer: 'Counsel',
      blockedAt: '2026-05-20 16:42:08',
      status: 'released',
    },
    {
      id: 'hf_sb_005',
      creativeId: 'hf_cr_0010',
      creativeHeadline: 'Hope Forward · TX Town Hall · join us live.',
      ruleViolated: 'YouTube branding · audio compliance · transcript provided',
      severity: 'info',
      reviewer: 'Auto-resolved',
      blockedAt: '2026-05-19 12:18:42',
      status: 'released',
    },
  ],
  providers: [
    {
      kind: 'meta_marketing',
      status: 'connected',
      accountLabel: 'act_19248317 (Hope Forward · US)',
      callsToday: 184,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:42 UTC',
    },
    {
      kind: 'google_ads',
      status: 'connected',
      accountLabel: 'customers/882-441-9120 · Hope Forward',
      callsToday: 92,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:38 UTC',
    },
    {
      kind: 'youtube',
      status: 'connected',
      accountLabel: 'YouTube · @HopeForwardOfficial',
      callsToday: 18,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:34 UTC',
    },
    {
      kind: 'claude_copy',
      status: 'connected',
      accountLabel: 'Anthropic · claude-3-5-sonnet',
      callsToday: 282,
      costCentsToday: 124,
      lastPingAt: '2026-05-24 09:41 UTC',
    },
    {
      kind: 'flux_image',
      status: 'connected',
      accountLabel: 'Replicate · black-forest-labs/flux-1.1-pro',
      callsToday: 64,
      costCentsToday: 256,
      lastPingAt: '2026-05-24 09:39 UTC',
    },
    {
      kind: 'heygen_avatar',
      status: 'sandbox',
      accountLabel: 'hg_org_b9 · sandbox · quota 412 left',
      callsToday: 4,
      costCentsToday: 168,
      lastPingAt: '2026-05-24 09:21 UTC',
    },
    {
      kind: 'anthropic_mod',
      status: 'connected',
      accountLabel: 'Anthropic moderation · per-creative scan',
      callsToday: 412,
      costCentsToday: 18,
      lastPingAt: '2026-05-24 09:42 UTC',
    },
    {
      kind: 'tiktok_marketing',
      status: 'not_connected',
      accountLabel: '— (Hope Forward brand restricts TikTok)',
      callsToday: 0,
      costCentsToday: 0,
      lastPingAt: '—',
    },
  ],
  pipelineCounts: { brief: 6, compose: 9, variation: 32, review: 14, publish: 18, measure: 84 },
  kpis: {
    creativesThisWeek: 84,
    safetyPassPct: 96.2,
    avgCostPerCreativeCents: 38,
    activeCampaigns: 9,
    rollingRoas: 5.4,
    aiAssistHoursSaved: 42,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// World Vision — AU charity (child sponsorship)
// ─────────────────────────────────────────────────────────────────────────────
const WORLD_VISION: AccountMarketing = {
  scopeLabel: 'World Vision · AU',
  currency: 'AUD',
  region: 'AU',
  vertical: 'charity',
  themes: [
    'charity_children',
    'charity_water',
    'charity_food',
    'charity_medical',
    'charity_disaster',
  ],
  channels: ['meta', 'google', 'youtube', 'email', 'sms'],
  creatives: [
    {
      id: 'wv_cr_0001',
      headline: 'Sponsor a child in Cebu — $50/month.',
      copy: 'World Vision AU · child sponsorship · ACNC-registered · tax-deductible · cancel anytime.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 14_200,
      conversions: 64,
      convRate: 4.1,
      roas: 5.4,
      liveAt: '2026-05-09',
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0002',
      headline: 'For every child sponsored in Cebu, a Knocker plants one tree.',
      copy: 'World Vision AU · child sponsorship · ACNC-registered · paid solicitor licensed VIC + NSW.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 12_840,
      conversions: 58,
      convRate: 4.0,
      roas: 5.2,
      liveAt: '2026-05-11',
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0003',
      headline: '3 in 5 Aussie families need help this winter.',
      copy: 'World Vision AU · winter appeal · SEIFA decile-9 targeting · tax-deductible.',
      theme: 'charity_food',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 10_420,
      conversions: 48,
      convRate: 3.9,
      roas: 5.7,
      liveAt: '2026-05-07',
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0004',
      headline: '1L of clean water for a Khmer village · $20.',
      copy: 'World Vision AU water program · Cambodia · ACNC · tax-deductible · 100% to wells.',
      theme: 'charity_water',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 6_120,
      conversions: 32,
      convRate: 3.6,
      roas: 4.4,
      liveAt: '2026-05-13',
    },
    {
      id: 'wv_cr_0005',
      headline: 'EOFY · double your tax refund · donate before 30 June.',
      copy: 'World Vision AU · End of Financial Year giving · ACNC-registered · receipt by email.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 18_400,
      conversions: 92,
      convRate: 4.2,
      roas: 6.1,
      liveAt: '2026-05-10',
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0006',
      headline: "Carlton's Knockers walked 312 km this week.",
      copy: 'World Vision AU · VIC field team update · ACNC-registered · paid solicitor licence ACT1239.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 4_820,
      conversions: 24,
      convRate: 3.4,
      roas: 4.1,
      liveAt: '2026-05-12',
      reviewerInitials: 'CT',
    },
    {
      id: 'wv_cr_0007',
      headline: 'A nurse in Khmer reaches your sponsored child every month.',
      copy: 'World Vision AU · child sponsorship · medical reach · ACNC-registered · tax-deductible.',
      theme: 'charity_medical',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 9_120,
      conversions: 38,
      convRate: 3.5,
      roas: 4.3,
      liveAt: '2026-05-08',
    },
    {
      id: 'wv_cr_0008',
      headline: 'Bushfire recovery · $40 funds a family for a week.',
      copy: 'World Vision AU · disaster relief · ACNC · NSW/VIC bushfire recovery · tax-deductible.',
      theme: 'charity_disaster',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 12_280,
      conversions: 56,
      convRate: 3.8,
      roas: 4.9,
      liveAt: '2026-05-06',
    },
    {
      id: 'wv_cr_0009',
      headline: 'Sponsor a child · pay nothing for the first month.',
      copy: 'World Vision AU · child sponsorship · first month free · ACNC-registered.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'image',
      status: 'blocked',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'CT',
    },
    {
      id: 'wv_cr_0010',
      headline: 'Help feed 100 Sydney families this winter.',
      copy: 'World Vision AU winter food drive · $25 covers a family · ACNC · tax-deductible.',
      theme: 'charity_food',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 7_240,
      conversions: 31,
      convRate: 3.2,
      roas: 4.1,
      liveAt: '2026-05-14',
    },
    {
      id: 'wv_cr_0011',
      headline: 'Cebu update · your sponsored child started school today.',
      copy: 'World Vision AU sponsor update · monthly email cadence · ACNC-registered.',
      theme: 'charity_children',
      channel: 'email',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0012',
      headline: 'Aussie kids on the line · sponsor a child in NT today.',
      copy: 'World Vision AU · NT remote programs · ACNC · paid solicitor licence WA0118.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 8_640,
      conversions: 41,
      convRate: 3.7,
      roas: 4.7,
      liveAt: '2026-05-15',
    },
    {
      id: 'wv_cr_0013',
      headline: 'YouTube doc · "A year in Cebu" · 14-min cut.',
      copy: 'World Vision AU · long-form documentary · sponsor drive Q3 · YouTube.',
      theme: 'charity_children',
      channel: 'youtube',
      format: 'video',
      status: 'review',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'wv_cr_0014',
      headline: 'EOFY SMS · "your tax refund could change a life"',
      copy: 'World Vision AU · EOFY SMS cadence · ACMA-compliant · explicit opt-in only.',
      theme: 'charity_children',
      channel: 'sms',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
  ],
  campaigns: [
    {
      id: 'wv_cmp_001',
      name: 'AU Child Sponsorship · Q3 push',
      channel: 'meta',
      status: 'active',
      budgetCents: 900_000,
      spendCents: 842_000,
      impressions: 1_142_810,
      clicks: 28_915,
      conversions: 542,
      ctrPct: 2.53,
      roas: 5.8,
      attribution: 'cold',
      startedAt: '2026-04-22',
    },
    {
      id: 'wv_cmp_002',
      name: 'EOFY Match · End of Financial Year',
      channel: 'meta',
      status: 'active',
      budgetCents: 1_200_000,
      spendCents: 982_000,
      impressions: 1_482_300,
      clicks: 38_410,
      conversions: 612,
      ctrPct: 2.59,
      roas: 6.4,
      attribution: 'retargeting',
      startedAt: '2026-05-04',
    },
    {
      id: 'wv_cmp_003',
      name: 'Bushfire Recovery · NSW/VIC',
      channel: 'google',
      status: 'active',
      budgetCents: 600_000,
      spendCents: 412_000,
      impressions: 312_400,
      clicks: 14_810,
      conversions: 218,
      ctrPct: 4.74,
      roas: 5.1,
      attribution: 'cold',
      startedAt: '2026-05-06',
    },
    {
      id: 'wv_cmp_004',
      name: 'Winter Appeal · SEIFA decile-9',
      channel: 'meta',
      status: 'active',
      budgetCents: 800_000,
      spendCents: 642_000,
      impressions: 884_200,
      clicks: 22_180,
      conversions: 382,
      ctrPct: 2.51,
      roas: 5.4,
      attribution: 'retargeting',
      startedAt: '2026-05-07',
    },
    {
      id: 'wv_cmp_005',
      name: 'YouTube doc · "A year in Cebu"',
      channel: 'youtube',
      status: 'scheduled',
      budgetCents: 700_000,
      spendCents: 0,
      impressions: 0,
      clicks: 0,
      conversions: 0,
      ctrPct: 0,
      roas: 0,
      attribution: 'cold',
      startedAt: '2026-05-28',
    },
    {
      id: 'wv_cmp_006',
      name: 'Sponsor update · email cadence',
      channel: 'email',
      status: 'active',
      budgetCents: 80_000,
      spendCents: 24_000,
      impressions: 84_100,
      clicks: 18_400,
      conversions: 142,
      ctrPct: 21.9,
      roas: 7.2,
      attribution: 'inside_sales',
      startedAt: '2026-05-12',
    },
    {
      id: 'wv_cmp_007',
      name: 'NT Remote · child sponsor lift',
      channel: 'meta',
      status: 'active',
      budgetCents: 400_000,
      spendCents: 282_000,
      impressions: 412_800,
      clicks: 10_840,
      conversions: 184,
      ctrPct: 2.62,
      roas: 4.6,
      attribution: 'cold',
      startedAt: '2026-05-15',
    },
  ],
  retargetingCohorts: [
    {
      id: 'wv_aud_001',
      name: 'NSW SEIFA-9 callbacks · 14d',
      source: '4,812 knocks · CALLBACK + NOT_HOME 14d',
      audienceSize: 4_812,
      reach: 84_210,
      ctrPct: 2.4,
      attributedConversions: 64,
      revenueCents: 576_000,
    },
    {
      id: 'wv_aud_002',
      name: 'VIC CALLBACK · won-call air-cover',
      source: '1,240 knocks · CALLBACK 21d',
      audienceSize: 1_240,
      reach: 24_310,
      ctrPct: 2.3,
      attributedConversions: 18,
      revenueCents: 162_000,
    },
    {
      id: 'wv_aud_003',
      name: 'EOFY · prior-year donors lapsed',
      source: 'Donors who lapsed 1 year+ · 3,420',
      audienceSize: 3_420,
      reach: 42_180,
      ctrPct: 3.8,
      attributedConversions: 112,
      revenueCents: 540_000,
    },
    {
      id: 'wv_aud_004',
      name: 'Site visit · /sponsor not signed',
      source: '/sponsor visitors · 30d · 5,210',
      audienceSize: 5_210,
      reach: 64_100,
      ctrPct: 3.4,
      attributedConversions: 142,
      revenueCents: 728_000,
    },
    {
      id: 'wv_aud_005',
      name: 'Bushfire donor · lookalike',
      source: 'NSW/VIC bushfire donors 30d · 1,420',
      audienceSize: 1_420,
      reach: 18_410,
      ctrPct: 2.7,
      attributedConversions: 41,
      revenueCents: 168_000,
    },
  ],
  brandRules: [
    {
      id: 'wv_br_001',
      category: 'charity',
      rule: 'ACNC fundraising standards · accurate program ratio',
      scope: 'AU (ACNC)',
      severity: 'critical',
    },
    {
      id: 'wv_br_002',
      category: 'charity',
      rule: 'ACMA Spam Act · explicit opt-in for SMS/email · proof retained',
      scope: 'AU (ACMA)',
      severity: 'critical',
    },
    {
      id: 'wv_br_003',
      category: 'charity',
      rule: 'Privacy Act / APP · PII consent + retention disclosure',
      scope: 'AU (OAIC)',
      severity: 'critical',
    },
    {
      id: 'wv_br_004',
      category: 'charity',
      rule: 'ACL 10-day cooling-off · door-to-door fundraising disclosure',
      scope: 'AU (ACCC)',
      severity: 'warn',
    },
    {
      id: 'wv_br_005',
      category: 'charity',
      rule: 'State-by-state paid solicitor licensing · NSW/VIC/WA/QLD/ACT',
      scope: 'AU (state regulators)',
      severity: 'warn',
    },
    {
      id: 'wv_br_006',
      category: 'charity',
      rule: 'ACNC · no "guaranteed impact" language',
      scope: 'AU (ACNC)',
      severity: 'warn',
    },
    {
      id: 'wv_br_007',
      category: 'generic',
      rule: 'No false-scarcity language ("last chance", "expires tonight")',
      scope: 'AU (ACCC)',
      severity: 'info',
    },
  ],
  recentBlocks: [
    {
      id: 'wv_sb_001',
      creativeId: 'wv_cr_0009',
      creativeHeadline: 'Sponsor a child · pay nothing for the first month.',
      ruleViolated: 'Charity AU · ACNC · misleading "free month" framing',
      severity: 'critical',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-23 14:38:09',
      status: 'pending',
    },
    {
      id: 'wv_sb_002',
      creativeId: 'wv_cr_0006',
      creativeHeadline: "Carlton's Knockers walked 312 km this week.",
      ruleViolated: 'Charity AU · VIC paid solicitor licence ref needed',
      severity: 'warn',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-22 11:18:42',
      status: 'released',
    },
    {
      id: 'wv_sb_003',
      creativeId: 'wv_cr_0014',
      creativeHeadline: 'EOFY SMS · "your tax refund could change a life"',
      ruleViolated: 'Charity AU · ACMA Spam Act · explicit opt-in proof required',
      severity: 'critical',
      reviewer: 'Brodie',
      blockedAt: '2026-05-21 09:31:18',
      status: 'rewritten',
    },
    {
      id: 'wv_sb_004',
      creativeId: 'wv_cr_0002',
      creativeHeadline: 'For every child sponsored in Cebu, a Knocker plants one tree.',
      ruleViolated: 'Charity AU · ACNC · tree-planting implies impact guarantee',
      severity: 'warn',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-20 16:42:08',
      status: 'released',
    },
    {
      id: 'wv_sb_005',
      creativeId: 'wv_cr_0005',
      creativeHeadline: 'EOFY · double your tax refund · donate before 30 June.',
      ruleViolated: 'Charity AU · ATO · "double your tax refund" needs context',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-19 12:18:42',
      status: 'released',
    },
  ],
  providers: [
    {
      kind: 'meta_marketing',
      status: 'connected',
      accountLabel: 'act_44820917 (World Vision · AU)',
      callsToday: 142,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:41 UTC',
    },
    {
      kind: 'google_ads',
      status: 'connected',
      accountLabel: 'customers/441-820-3091 · World Vision AU',
      callsToday: 64,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:36 UTC',
    },
    {
      kind: 'youtube',
      status: 'connected',
      accountLabel: 'YouTube · @WorldVisionAU',
      callsToday: 12,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:28 UTC',
    },
    {
      kind: 'claude_copy',
      status: 'connected',
      accountLabel: 'Anthropic · claude-3-5-sonnet',
      callsToday: 198,
      costCentsToday: 92,
      lastPingAt: '2026-05-24 09:40 UTC',
    },
    {
      kind: 'flux_image',
      status: 'connected',
      accountLabel: 'Replicate · flux-1.1-pro · AU region',
      callsToday: 42,
      costCentsToday: 168,
      lastPingAt: '2026-05-24 09:34 UTC',
    },
    {
      kind: 'heygen_avatar',
      status: 'sandbox',
      accountLabel: 'hg_org_wv · sandbox · evaluating',
      callsToday: 2,
      costCentsToday: 84,
      lastPingAt: '2026-05-24 09:14 UTC',
    },
    {
      kind: 'anthropic_mod',
      status: 'connected',
      accountLabel: 'Anthropic moderation · per-creative scan',
      callsToday: 312,
      costCentsToday: 14,
      lastPingAt: '2026-05-24 09:41 UTC',
    },
    {
      kind: 'tiktok_marketing',
      status: 'not_connected',
      accountLabel: '— (World Vision AU brand policy)',
      callsToday: 0,
      costCentsToday: 0,
      lastPingAt: '—',
    },
  ],
  pipelineCounts: { brief: 4, compose: 7, variation: 26, review: 10, publish: 14, measure: 62 },
  kpis: {
    creativesThisWeek: 62,
    safetyPassPct: 97.4,
    avgCostPerCreativeCents: 41,
    activeCampaigns: 7,
    rollingRoas: 4.8,
    aiAssistHoursSaved: 31,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// PestMax — US commercial pest control
// ─────────────────────────────────────────────────────────────────────────────
const PESTMAX: AccountMarketing = {
  scopeLabel: 'PestMax · US',
  currency: 'USD',
  region: 'US',
  vertical: 'commercial',
  themes: ['pest_control', 'home_services', 'security'],
  channels: ['meta', 'google', 'tiktok', 'email'],
  creatives: [
    {
      id: 'pm_cr_0001',
      headline: "Don't share your meal with roaches · Texas-licensed.",
      copy: 'PestMax · Houston + Austin · same-day service · TX-CPM 8845.',
      theme: 'pest_control',
      channel: 'tiktok',
      format: 'video',
      status: 'published',
      spendCents: 18_400,
      conversions: 42,
      convRate: 3.8,
      roas: 4.9,
      liveAt: '2026-05-10',
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0002',
      headline: 'Year-round pest protection · free re-treat included.',
      copy: 'PestMax · annual plan $48/mo · TX-licensed CPM 8845 · EPA-registered products.',
      theme: 'pest_control',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 12_840,
      conversions: 38,
      convRate: 3.5,
      roas: 4.4,
      liveAt: '2026-05-09',
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0003',
      headline: 'AZ termite season starts in May · we knock at 9am.',
      copy: 'PestMax · Arizona termite specialists · OPM 9112 · EPA · same-week service.',
      theme: 'pest_control',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 9_240,
      conversions: 28,
      convRate: 3.2,
      roas: 4.1,
      liveAt: '2026-05-11',
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0004',
      headline: 'Bedbug? We come tonight. PestMax 24/7.',
      copy: 'PestMax bedbug emergency · TX-CPM 8845 · same-night response · 90-day guarantee.',
      theme: 'pest_control',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 8_120,
      conversions: 24,
      convRate: 4.1,
      roas: 5.2,
      liveAt: '2026-05-08',
    },
    {
      id: 'pm_cr_0005',
      headline: 'Roach-free in 1 visit or we come back free.',
      copy: 'PestMax 1-visit guarantee · TX + AZ · EPA-registered · CPM 8845 / OPM 9112.',
      theme: 'pest_control',
      channel: 'tiktok',
      format: 'video',
      status: 'review',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0006',
      headline: 'Warranty renewal · $39/mo locks in 2026 rates.',
      copy: 'PestMax loyalty renewal · prior customers · TX + AZ · CPM 8845.',
      theme: 'pest_control',
      channel: 'email',
      format: 'text',
      status: 'published',
      spendCents: 1_240,
      conversions: 41,
      convRate: 8.2,
      roas: 11.2,
      liveAt: '2026-05-14',
    },
    {
      id: 'pm_cr_0007',
      headline: 'PestMax · we live where you live.',
      copy: 'Local techs · TX + AZ · CPM 8845 · OPM 9112 · neighborhood field crews.',
      theme: 'home_services',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 6_840,
      conversions: 18,
      convRate: 2.9,
      roas: 3.6,
      liveAt: '2026-05-12',
    },
    {
      id: 'pm_cr_0008',
      headline: 'Mosquito-free yard · before your BBQ.',
      copy: 'PestMax mosquito service · 21-day window · EPA · TX + AZ · same-week appt.',
      theme: 'pest_control',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 7_420,
      conversions: 22,
      convRate: 3.4,
      roas: 4.2,
      liveAt: '2026-05-13',
    },
    {
      id: 'pm_cr_0009',
      headline: 'Kills 100% of roaches in one visit.',
      copy: 'PestMax · 1-visit roach plan · TX-CPM 8845.',
      theme: 'pest_control',
      channel: 'google',
      format: 'image',
      status: 'blocked',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0010',
      headline: 'Free inspection · book today, treat tomorrow.',
      copy: 'PestMax free home inspection · TX + AZ · EPA-registered products · CPM 8845.',
      theme: 'pest_control',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 5_120,
      conversions: 14,
      convRate: 2.6,
      roas: 3.4,
      liveAt: '2026-05-15',
    },
    {
      id: 'pm_cr_0011',
      headline: 'Spider, ant, roach · one plan for all.',
      copy: 'PestMax annual plan · $48/mo · TX-CPM 8845 · EPA-registered · free re-treat.',
      theme: 'pest_control',
      channel: 'tiktok',
      format: 'video',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'pm_cr_0012',
      headline: 'Why your neighbours switched to PestMax.',
      copy: 'PestMax · TX + AZ · testimonial-led · CPM 8845 · 1,200+ 5-star reviews.',
      theme: 'home_services',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 6_240,
      conversions: 19,
      convRate: 3.0,
      roas: 3.7,
      liveAt: '2026-05-12',
    },
  ],
  campaigns: [
    {
      id: 'pm_cmp_001',
      name: 'Texas Summer Pest Push · roach focus',
      channel: 'meta',
      status: 'active',
      budgetCents: 400_000,
      spendCents: 312_000,
      impressions: 412_800,
      clicks: 14_810,
      conversions: 218,
      ctrPct: 3.59,
      roas: 5.4,
      attribution: 'retargeting',
      startedAt: '2026-05-04',
    },
    {
      id: 'pm_cmp_002',
      name: 'AZ Termite Season · May surge',
      channel: 'google',
      status: 'active',
      budgetCents: 320_000,
      spendCents: 242_000,
      impressions: 184_200,
      clicks: 8_410,
      conversions: 142,
      ctrPct: 4.57,
      roas: 4.8,
      attribution: 'cold',
      startedAt: '2026-05-08',
    },
    {
      id: 'pm_cmp_003',
      name: 'Warranty Renewal Q3 · loyalty',
      channel: 'email',
      status: 'active',
      budgetCents: 40_000,
      spendCents: 8_400,
      impressions: 24_100,
      clicks: 3_840,
      conversions: 184,
      ctrPct: 15.9,
      roas: 12.4,
      attribution: 'inside_sales',
      startedAt: '2026-05-12',
    },
    {
      id: 'pm_cmp_004',
      name: 'TikTok Brand · "roach tour" series',
      channel: 'tiktok',
      status: 'active',
      budgetCents: 220_000,
      spendCents: 184_000,
      impressions: 612_400,
      clicks: 22_400,
      conversions: 92,
      ctrPct: 3.66,
      roas: 3.9,
      attribution: 'cold',
      startedAt: '2026-05-10',
    },
    {
      id: 'pm_cmp_005',
      name: 'Mosquito · BBQ-season Meta push',
      channel: 'meta',
      status: 'paused',
      budgetCents: 180_000,
      spendCents: 142_000,
      impressions: 282_400,
      clicks: 7_120,
      conversions: 84,
      ctrPct: 2.52,
      roas: 3.6,
      attribution: 'cold',
      startedAt: '2026-05-02',
    },
    {
      id: 'pm_cmp_006',
      name: 'Bedbug Emergency · 24/7 Google Search',
      channel: 'google',
      status: 'active',
      budgetCents: 220_000,
      spendCents: 168_000,
      impressions: 91_200,
      clicks: 6_410,
      conversions: 118,
      ctrPct: 7.03,
      roas: 6.4,
      attribution: 'cold',
      startedAt: '2026-05-09',
    },
  ],
  retargetingCohorts: [
    {
      id: 'pm_aud_001',
      name: 'Knocked / quoted · not converted 14d',
      source: '1,184 knocks · QUOTED 14d · TX + AZ',
      audienceSize: 1_184,
      reach: 14_210,
      ctrPct: 2.8,
      attributedConversions: 11,
      revenueCents: 98_200,
    },
    {
      id: 'pm_aud_002',
      name: 'Service ended 6mo ago · re-engage',
      source: 'Cancelled customers 6mo · 482',
      audienceSize: 482,
      reach: 8_120,
      ctrPct: 3.1,
      attributedConversions: 14,
      revenueCents: 124_000,
    },
    {
      id: 'pm_aud_003',
      name: 'TX CALLBACK 21d',
      source: '420 knocks · CALLBACK 21d',
      audienceSize: 420,
      reach: 4_120,
      ctrPct: 2.6,
      attributedConversions: 6,
      revenueCents: 53_400,
    },
    {
      id: 'pm_aud_004',
      name: 'AZ termite-season lookalike',
      source: 'AZ termite buyers prior year · 820',
      audienceSize: 820,
      reach: 12_400,
      ctrPct: 3.4,
      attributedConversions: 22,
      revenueCents: 184_000,
    },
    {
      id: 'pm_aud_005',
      name: 'Site visit · /bedbug not booked',
      source: '/bedbug visitors 14d · 612',
      audienceSize: 612,
      reach: 6_420,
      ctrPct: 4.2,
      attributedConversions: 18,
      revenueCents: 142_000,
    },
  ],
  brandRules: [
    {
      id: 'pm_br_001',
      category: 'pest',
      rule: 'FTC truth-in-advertising · no unsubstantiated efficacy claims',
      scope: 'US (FTC)',
      severity: 'critical',
    },
    {
      id: 'pm_br_002',
      category: 'pest',
      rule: 'EPA chemical disclosure · active ingredient on product page',
      scope: 'US (EPA)',
      severity: 'critical',
    },
    {
      id: 'pm_br_003',
      category: 'pest',
      rule: 'No health claims · cannot say "kills disease-carrying pests"',
      scope: 'US (FTC, EPA)',
      severity: 'warn',
    },
    {
      id: 'pm_br_004',
      category: 'pest',
      rule: 'State pest-control licensing display · TX-CPM 8845 / AZ-OPM 9112',
      scope: 'US (TX TDA, AZ OPM)',
      severity: 'warn',
    },
    {
      id: 'pm_br_005',
      category: 'pest',
      rule: 'No "100% guarantee" without contract terms in ad',
      scope: 'US (FTC)',
      severity: 'warn',
    },
    {
      id: 'pm_br_006',
      category: 'generic',
      rule: 'No "100%" near "kill" / "eliminate" / "destroy"',
      scope: 'US (FTC)',
      severity: 'info',
    },
  ],
  recentBlocks: [
    {
      id: 'pm_sb_001',
      creativeId: 'pm_cr_0009',
      creativeHeadline: 'Kills 100% of roaches in one visit.',
      ruleViolated: 'Pest US · ACL substantiation · efficacy claim',
      severity: 'critical',
      reviewer: 'Brodie',
      blockedAt: '2026-05-23 14:22:08',
      status: 'rewritten',
    },
    {
      id: 'pm_sb_002',
      creativeId: 'pm_cr_0003',
      creativeHeadline: 'AZ termite season starts in May · we knock at 9am.',
      ruleViolated: 'Pest US · EPA chemical disclosure absent',
      severity: 'info',
      reviewer: 'Auto-resolved',
      blockedAt: '2026-05-22 17:48:21',
      status: 'released',
    },
    {
      id: 'pm_sb_003',
      creativeId: 'pm_cr_0004',
      creativeHeadline: 'Bedbug? We come tonight. PestMax 24/7.',
      ruleViolated: 'Pest US · TX-CPM 8845 licence display needed',
      severity: 'warn',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-21 09:31:18',
      status: 'released',
    },
    {
      id: 'pm_sb_004',
      creativeId: 'pm_cr_0001',
      creativeHeadline: "Don't share your meal with roaches · Texas-licensed.",
      ruleViolated: 'Pest US · FTC · "Texas-licensed" needs CPM number adjacent',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-20 16:42:08',
      status: 'released',
    },
    {
      id: 'pm_sb_005',
      creativeId: 'pm_cr_0005',
      creativeHeadline: 'Roach-free in 1 visit or we come back free.',
      ruleViolated: 'Pest US · FTC · guarantee needs contract reference',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-19 12:18:42',
      status: 'pending',
    },
  ],
  providers: [
    {
      kind: 'meta_marketing',
      status: 'connected',
      accountLabel: 'act_88204918 (PestMax · US)',
      callsToday: 84,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:41 UTC',
    },
    {
      kind: 'google_ads',
      status: 'connected',
      accountLabel: 'customers/008-882-0091 · PestMax',
      callsToday: 142,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:38 UTC',
    },
    {
      kind: 'tiktok_marketing',
      status: 'connected',
      accountLabel: 'TikTok Ads · pestmax_tx · sandbox graduated',
      callsToday: 28,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:34 UTC',
    },
    {
      kind: 'claude_copy',
      status: 'connected',
      accountLabel: 'Anthropic · claude-3-5-sonnet',
      callsToday: 112,
      costCentsToday: 48,
      lastPingAt: '2026-05-24 09:40 UTC',
    },
    {
      kind: 'flux_image',
      status: 'connected',
      accountLabel: 'Replicate · flux-1.1-pro',
      callsToday: 38,
      costCentsToday: 152,
      lastPingAt: '2026-05-24 09:36 UTC',
    },
    {
      kind: 'higgsfield_video',
      status: 'sandbox',
      accountLabel: 'hf_org_pm · sandbox · TikTok video',
      callsToday: 6,
      costCentsToday: 188,
      lastPingAt: '2026-05-24 09:21 UTC',
    },
    {
      kind: 'anthropic_mod',
      status: 'connected',
      accountLabel: 'Anthropic moderation · per-creative scan',
      callsToday: 184,
      costCentsToday: 8,
      lastPingAt: '2026-05-24 09:41 UTC',
    },
  ],
  pipelineCounts: { brief: 3, compose: 6, variation: 14, review: 5, publish: 8, measure: 38 },
  kpis: {
    creativesThisWeek: 38,
    safetyPassPct: 92.1,
    avgCostPerCreativeCents: 32,
    activeCampaigns: 5,
    rollingRoas: 6.2,
    aiAssistHoursSaved: 19,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Gold Coast Hospital — AU healthcare foundation
// ─────────────────────────────────────────────────────────────────────────────
const GOLD_COAST_HOSPITAL: AccountMarketing = {
  scopeLabel: 'Gold Coast Hospital · AU',
  currency: 'AUD',
  region: 'AU',
  vertical: 'healthcare',
  themes: ['healthcare', 'charity_medical', 'charity_children'],
  channels: ['meta', 'google', 'email'],
  creatives: [
    {
      id: 'gc_cr_0001',
      headline: 'Help fund the new oncology wing · Gold Coast Hospital.',
      copy: 'Gold Coast Hospital Foundation · capital campaign · tax-deductible · ACNC-registered.',
      theme: 'healthcare',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 18_400,
      conversions: 36,
      convRate: 3.4,
      roas: 4.6,
      liveAt: '2026-05-09',
      reviewerInitials: 'B',
    },
    {
      id: 'gc_cr_0002',
      headline: 'One pledge a month feeds research at GCH.',
      copy: 'Gold Coast Hospital Foundation · monthly giving · ACNC-registered · TGA-compliant.',
      theme: 'healthcare',
      channel: 'meta',
      format: 'carousel',
      status: 'published',
      spendCents: 9_240,
      conversions: 22,
      convRate: 2.8,
      roas: 3.4,
      liveAt: '2026-05-11',
      reviewerInitials: 'CT',
    },
    {
      id: 'gc_cr_0003',
      headline: 'Our nurses thank you for your bequest.',
      copy: 'Gold Coast Hospital Foundation · bequest program · ACNC-registered · legal forms inside.',
      theme: 'healthcare',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 7_120,
      conversions: 14,
      convRate: 2.4,
      roas: 3.1,
      liveAt: '2026-05-12',
      reviewerInitials: 'CT',
    },
    {
      id: 'gc_cr_0004',
      headline: 'New oncology wing · open 2027 · be part of it.',
      copy: 'Gold Coast Hospital Foundation · capital campaign · ACNC · TGA · AHPRA-compliant.',
      theme: 'healthcare',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 5_840,
      conversions: 12,
      convRate: 2.6,
      roas: 3.3,
      liveAt: '2026-05-13',
    },
    {
      id: 'gc_cr_0005',
      headline: 'GCH paediatric wing · meet the team.',
      copy: 'Gold Coast Hospital Foundation · paediatric appeal · ACNC · TGA-compliant content.',
      theme: 'charity_children',
      channel: 'meta',
      format: 'video',
      status: 'published',
      spendCents: 8_420,
      conversions: 18,
      convRate: 2.9,
      roas: 3.6,
      liveAt: '2026-05-08',
    },
    {
      id: 'gc_cr_0006',
      headline: 'Major gifts · EOFY · double your impact.',
      copy: 'Gold Coast Hospital Foundation · major-gifts EOFY · ACNC · tax-deductible · invitation only.',
      theme: 'healthcare',
      channel: 'email',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'gc_cr_0007',
      headline: 'A patient story · cancer-free at 47.',
      copy: 'Gold Coast Hospital · patient testimonial · AHPRA consent on file · ACNC fundraising.',
      theme: 'charity_medical',
      channel: 'meta',
      format: 'video',
      status: 'review',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'CT',
    },
    {
      id: 'gc_cr_0008',
      headline: 'Help fund research at Gold Coast Hospital.',
      copy: 'GCH Foundation · research appeal · ACNC · monthly tax-deductible.',
      theme: 'healthcare',
      channel: 'google',
      format: 'image',
      status: 'published',
      spendCents: 4_120,
      conversions: 9,
      convRate: 2.2,
      roas: 2.9,
      liveAt: '2026-05-14',
    },
    {
      id: 'gc_cr_0009',
      headline: 'Capital campaign · we are 74% there.',
      copy: 'Gold Coast Hospital Foundation · capital campaign · progress update · ACNC.',
      theme: 'healthcare',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 6_120,
      conversions: 11,
      convRate: 2.3,
      roas: 3.0,
      liveAt: '2026-05-15',
    },
    {
      id: 'gc_cr_0010',
      headline: 'GCH paediatric · sponsor a hospital room.',
      copy: 'Gold Coast Hospital Foundation · room-naming opportunity · major gifts · ACNC.',
      theme: 'charity_children',
      channel: 'email',
      format: 'text',
      status: 'approved',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
      reviewerInitials: 'B',
    },
    {
      id: 'gc_cr_0011',
      headline: 'Major-gift donors · annual private briefing.',
      copy: 'Gold Coast Hospital Foundation · invitation-only event · ACNC fundraising.',
      theme: 'healthcare',
      channel: 'email',
      format: 'text',
      status: 'draft',
      spendCents: 0,
      conversions: 0,
      convRate: 0,
      roas: 0,
    },
    {
      id: 'gc_cr_0012',
      headline: 'Every bequest builds a wing.',
      copy: 'Gold Coast Hospital Foundation · bequest program · ACNC · solicitor referrals listed.',
      theme: 'healthcare',
      channel: 'meta',
      format: 'image',
      status: 'published',
      spendCents: 5_420,
      conversions: 8,
      convRate: 2.0,
      roas: 2.7,
      liveAt: '2026-05-12',
    },
  ],
  campaigns: [
    {
      id: 'gc_cmp_001',
      name: 'Capital Campaign Q3 · oncology wing',
      channel: 'meta',
      status: 'active',
      budgetCents: 600_000,
      spendCents: 412_000,
      impressions: 412_800,
      clicks: 9_840,
      conversions: 142,
      ctrPct: 2.38,
      roas: 4.1,
      attribution: 'cold',
      startedAt: '2026-05-04',
    },
    {
      id: 'gc_cmp_002',
      name: 'Bequest Drive Q4 · estate planning',
      channel: 'email',
      status: 'active',
      budgetCents: 40_000,
      spendCents: 8_400,
      impressions: 12_400,
      clicks: 1_840,
      conversions: 32,
      ctrPct: 14.8,
      roas: 6.4,
      attribution: 'inside_sales',
      startedAt: '2026-05-12',
    },
    {
      id: 'gc_cmp_003',
      name: 'EOFY Major Gifts · invitation-only',
      channel: 'email',
      status: 'scheduled',
      budgetCents: 20_000,
      spendCents: 0,
      impressions: 0,
      clicks: 0,
      conversions: 0,
      ctrPct: 0,
      roas: 0,
      attribution: 'inside_sales',
      startedAt: '2026-05-30',
    },
    {
      id: 'gc_cmp_004',
      name: 'Paediatric appeal · QLD high-income',
      channel: 'meta',
      status: 'active',
      budgetCents: 220_000,
      spendCents: 142_000,
      impressions: 184_200,
      clicks: 4_120,
      conversions: 41,
      ctrPct: 2.24,
      roas: 3.4,
      attribution: 'cold',
      startedAt: '2026-05-08',
    },
    {
      id: 'gc_cmp_005',
      name: 'Google Search · "donate Gold Coast Hospital"',
      channel: 'google',
      status: 'active',
      budgetCents: 120_000,
      spendCents: 82_000,
      impressions: 28_400,
      clicks: 1_420,
      conversions: 22,
      ctrPct: 5.0,
      roas: 3.1,
      attribution: 'cold',
      startedAt: '2026-05-06',
    },
  ],
  retargetingCohorts: [
    {
      id: 'gc_aud_001',
      name: 'QLD NOT_HOME 14d · high-income',
      source: '820 knocks · NOT_HOME 14d · QLD high-income postcodes',
      audienceSize: 820,
      reach: 12_400,
      ctrPct: 2.2,
      attributedConversions: 8,
      revenueCents: 480_000,
    },
    {
      id: 'gc_aud_002',
      name: 'Prior-year donors lapsed · 12mo',
      source: 'Donors lapsed 12+ mo · 612',
      audienceSize: 612,
      reach: 8_240,
      ctrPct: 3.4,
      attributedConversions: 14,
      revenueCents: 280_000,
    },
    {
      id: 'gc_aud_003',
      name: 'Capital campaign visitors · /wing',
      source: '/wing visitors 30d · 412',
      audienceSize: 412,
      reach: 6_120,
      ctrPct: 2.8,
      attributedConversions: 9,
      revenueCents: 168_000,
    },
    {
      id: 'gc_aud_004',
      name: 'Major-gift prospects · lookalike',
      source: 'Existing major donors · 84',
      audienceSize: 84,
      reach: 3_120,
      ctrPct: 4.1,
      attributedConversions: 4,
      revenueCents: 240_000,
    },
  ],
  brandRules: [
    {
      id: 'gc_br_001',
      category: 'healthcare',
      rule: 'TGA therapeutic-claims guidelines · no implied medical efficacy',
      scope: 'AU (TGA)',
      severity: 'critical',
    },
    {
      id: 'gc_br_002',
      category: 'healthcare',
      rule: 'AHPRA advertising guidelines for regulated health services',
      scope: 'AU (AHPRA)',
      severity: 'critical',
    },
    {
      id: 'gc_br_003',
      category: 'healthcare',
      rule: 'No patient testimonials without explicit recorded consent',
      scope: 'AU (AHPRA, Privacy Act)',
      severity: 'critical',
    },
    {
      id: 'gc_br_004',
      category: 'charity',
      rule: 'ACNC fundraising standards · accurate program ratio',
      scope: 'AU (ACNC)',
      severity: 'critical',
    },
    {
      id: 'gc_br_005',
      category: 'charity',
      rule: 'QLD state fundraising licensing · QFC ref display',
      scope: 'AU (QLD OFT)',
      severity: 'warn',
    },
    {
      id: 'gc_br_006',
      category: 'charity',
      rule: 'Bequest solicitations · solicitor referral required in creative',
      scope: 'AU (QLD QLS)',
      severity: 'warn',
    },
  ],
  recentBlocks: [
    {
      id: 'gc_sb_001',
      creativeId: 'gc_cr_0007',
      creativeHeadline: 'A patient story · cancer-free at 47.',
      ruleViolated: 'Healthcare AU · AHPRA · patient testimonial consent required',
      severity: 'critical',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-23 14:38:09',
      status: 'pending',
    },
    {
      id: 'gc_sb_002',
      creativeId: 'gc_cr_0001',
      creativeHeadline: 'Help fund the new oncology wing · Gold Coast Hospital.',
      ruleViolated: 'Healthcare AU · TGA · "fund" implies treatment outcomes',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-22 11:18:42',
      status: 'released',
    },
    {
      id: 'gc_sb_003',
      creativeId: 'gc_cr_0005',
      creativeHeadline: 'GCH paediatric wing · meet the team.',
      ruleViolated: 'Healthcare AU · AHPRA · clinician identity disclosure',
      severity: 'warn',
      reviewer: 'Compliance team',
      blockedAt: '2026-05-21 09:31:18',
      status: 'released',
    },
    {
      id: 'gc_sb_004',
      creativeId: 'gc_cr_0012',
      creativeHeadline: 'Every bequest builds a wing.',
      ruleViolated: 'Charity AU · QLS · bequest needs solicitor referral',
      severity: 'warn',
      reviewer: 'Brodie',
      blockedAt: '2026-05-20 16:42:08',
      status: 'rewritten',
    },
  ],
  providers: [
    {
      kind: 'meta_marketing',
      status: 'connected',
      accountLabel: 'act_99201882 (Gold Coast Hospital · AU)',
      callsToday: 38,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:38 UTC',
    },
    {
      kind: 'google_ads',
      status: 'connected',
      accountLabel: 'customers/198-244-0019 · Gold Coast Hospital',
      callsToday: 18,
      costCentsToday: 0,
      lastPingAt: '2026-05-24 09:30 UTC',
    },
    {
      kind: 'claude_copy',
      status: 'connected',
      accountLabel: 'Anthropic · claude-3-5-sonnet',
      callsToday: 42,
      costCentsToday: 12,
      lastPingAt: '2026-05-24 09:36 UTC',
    },
    {
      kind: 'flux_image',
      status: 'sandbox',
      accountLabel: 'Replicate · flux-1.1-pro · sandbox · TGA review queue',
      callsToday: 8,
      costCentsToday: 32,
      lastPingAt: '2026-05-24 09:24 UTC',
    },
    {
      kind: 'anthropic_mod',
      status: 'connected',
      accountLabel: 'Anthropic moderation · TGA-aware ruleset',
      callsToday: 64,
      costCentsToday: 4,
      lastPingAt: '2026-05-24 09:36 UTC',
    },
  ],
  pipelineCounts: { brief: 1, compose: 2, variation: 6, review: 2, publish: 4, measure: 14 },
  kpis: {
    creativesThisWeek: 14,
    safetyPassPct: 98.6,
    avgCostPerCreativeCents: 28,
    activeCampaigns: 3,
    rollingRoas: 3.9,
    aiAssistHoursSaved: 6,
  },
};

export const ACCOUNT_MARKETING: Record<string, AccountMarketing> = {
  'hope-forward': HOPE_FORWARD,
  'world-vision': WORLD_VISION,
  pestmax: PESTMAX,
  'gold-coast-hospital': GOLD_COAST_HOSPITAL,
};

export function getAccountMarketing(slug: string): AccountMarketing | undefined {
  return ACCOUNT_MARKETING[slug];
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers shared across per-account marketing-studio surfaces
// ─────────────────────────────────────────────────────────────────────────────

export const CHANNEL_LABEL: Record<Channel, string> = {
  meta: 'Meta',
  google: 'Google',
  tiktok: 'TikTok',
  youtube: 'YouTube',
  email: 'Email',
  sms: 'SMS',
};

export const CHANNEL_BADGE: Record<Channel, string> = {
  meta: 'bg-blue-100 text-blue-700',
  google: 'bg-amber-100 text-amber-700',
  tiktok: 'bg-rose-100 text-rose-700',
  youtube: 'bg-red-100 text-red-700',
  email: 'bg-emerald-100 text-emerald-700',
  sms: 'bg-violet-100 text-violet-700',
};

export const PROVIDER_LABEL: Record<string, string> = {
  meta_marketing: 'Meta Marketing',
  google_ads: 'Google Ads',
  tiktok_marketing: 'TikTok Marketing',
  youtube: 'YouTube',
  claude_copy: 'Anthropic Claude (copy)',
  openai_copy: 'OpenAI (copy fallback)',
  flux_image: 'FLUX 1.1 Pro (image)',
  ideogram_image: 'Ideogram (image)',
  higgsfield_video: 'Higgsfield (video)',
  runway_video: 'Runway Gen-3 (video)',
  heygen_avatar: 'HeyGen (avatar)',
  anthropic_mod: 'Anthropic moderation',
};

export const PROVIDER_INITIALS: Record<string, string> = {
  meta_marketing: 'M',
  google_ads: 'G',
  tiktok_marketing: 'T',
  youtube: 'YT',
  claude_copy: 'A',
  openai_copy: 'O',
  flux_image: 'F',
  ideogram_image: 'I',
  higgsfield_video: 'H',
  runway_video: 'R',
  heygen_avatar: 'HG',
  anthropic_mod: 'AM',
};

export const PROVIDER_GRADIENT: Record<string, string> = {
  meta_marketing: 'from-blue-600 to-indigo-700',
  google_ads: 'from-emerald-600 to-teal-700',
  tiktok_marketing: 'from-pink-600 to-rose-700',
  youtube: 'from-red-600 to-rose-700',
  claude_copy: 'from-orange-500 to-red-600',
  openai_copy: 'from-slate-700 to-slate-900',
  flux_image: 'from-cyan-600 to-blue-700',
  ideogram_image: 'from-fuchsia-600 to-pink-700',
  higgsfield_video: 'from-amber-600 to-orange-700',
  runway_video: 'from-zinc-600 to-zinc-800',
  heygen_avatar: 'from-green-600 to-emerald-700',
  anthropic_mod: 'from-orange-600 to-amber-700',
};
