/**
 * Per-account fleet + zone fixtures for live satellite maps.
 *
 * Each sub-account gets a scoped slice of FleetRep + AiZone data, with its
 * own map center/zoom appropriate to where the business operates. Counts are
 * sized for legibility on the map (12 max per account), not 1:1 with the real
 * rosters in `accounts.ts`.
 */

import type { FleetRep, AiZone } from './fleet-reps';

export interface AccountFleetData {
  /** [lat, lng] for initial map center */
  center: [number, number];
  zoom: number;
  reps: FleetRep[];
  zones: AiZone[];
  /** Display label for the floating "Live · …" badge */
  scopeLabel: string;
}

export const ACCOUNT_FLEET: Record<string, AccountFleetData> = {
  // ─────────────────────────────────────────────────────────────────────────
  // Hope Forward · US charity · 12 reps across Texas
  // ─────────────────────────────────────────────────────────────────────────
  'hope-forward': {
    center: [31.2, -97.0],
    zoom: 6,
    scopeLabel: 'Hope Forward · US',
    reps: [
      // Austin cluster (30.27, -97.74) — 4 reps
      {
        id: 'hf1',
        initials: 'JM',
        name: 'Jordan Mosley',
        account: 'Hope Forward',
        lat: 30.2672,
        lng: -97.7431,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 12m',
        knocksToday: 84,
        conversionsToday: 31,
        lastKnockMin: 3,
        territory: 'Austin East',
      },
      {
        id: 'hf2',
        initials: 'JD',
        name: 'Jada Davis',
        account: 'Hope Forward',
        lat: 30.2515,
        lng: -97.7186,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 08m',
        knocksToday: 91,
        conversionsToday: 22,
        lastKnockMin: 1,
        territory: 'Austin Central',
      },
      {
        id: 'hf3',
        initials: 'AR',
        name: 'Aaliyah Reed',
        account: 'Hope Forward',
        lat: 30.2898,
        lng: -97.7589,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 15m',
        knocksToday: 78,
        conversionsToday: 18,
        lastKnockMin: 7,
        territory: 'Austin North',
      },
      {
        id: 'hf4',
        initials: 'TM',
        name: 'Tomás Mendez',
        account: 'Hope Forward',
        lat: 30.2451,
        lng: -97.7299,
        status: 'break',
        shiftStart: '09:00',
        hoursToday: '3h 45m · LUNCH',
        knocksToday: 64,
        conversionsToday: 14,
        lastKnockMin: 28,
        territory: 'Austin South',
      },

      // Dallas / Plano cluster (32.78, -96.80) — 4 reps
      {
        id: 'hf5',
        initials: 'AM',
        name: 'Asha Mehta',
        account: 'Hope Forward',
        lat: 32.7821,
        lng: -96.8005,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 42m',
        knocksToday: 66,
        conversionsToday: 12,
        lastKnockMin: 5,
        territory: 'Dallas Metro',
      },
      {
        id: 'hf6',
        initials: 'CS',
        name: 'Cameron Singh',
        account: 'Hope Forward',
        lat: 32.7901,
        lng: -96.8214,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 30m',
        knocksToday: 58,
        conversionsToday: 11,
        lastKnockMin: 4,
        territory: 'Dallas North',
      },
      {
        id: 'hf7',
        initials: 'RV',
        name: 'Riley Vargas',
        account: 'Hope Forward',
        lat: 33.0198,
        lng: -96.6989,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '3h 22m',
        knocksToday: 49,
        conversionsToday: 9,
        lastKnockMin: 6,
        territory: 'Plano',
      },
      {
        id: 'hf8',
        initials: 'EB',
        name: 'Eli Bautista',
        account: 'Hope Forward',
        lat: 33.0044,
        lng: -96.7186,
        status: 'idle',
        shiftStart: '09:30',
        hoursToday: '3h 50m',
        knocksToday: 41,
        conversionsToday: 6,
        lastKnockMin: 22,
        territory: 'Plano',
      },

      // Houston cluster (29.76, -95.37) — 4 reps
      {
        id: 'hf9',
        initials: 'KP',
        name: 'Kim Park',
        account: 'Hope Forward',
        lat: 29.7589,
        lng: -95.3676,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 05m',
        knocksToday: 71,
        conversionsToday: 15,
        lastKnockMin: 4,
        territory: 'Houston Central',
      },
      {
        id: 'hf10',
        initials: 'DR',
        name: 'Devon Russell',
        account: 'Hope Forward',
        lat: 29.7434,
        lng: -95.3512,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 11m',
        knocksToday: 58,
        conversionsToday: 11,
        lastKnockMin: 2,
        territory: 'Houston SE',
      },
      {
        id: 'hf11',
        initials: 'ML',
        name: 'Marcus Lee',
        account: 'Hope Forward',
        lat: 29.7782,
        lng: -95.3951,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 00m',
        knocksToday: 62,
        conversionsToday: 13,
        lastKnockMin: 3,
        territory: 'Houston West',
      },
      {
        id: 'hf12',
        initials: 'NK',
        name: 'Naomi Kowalski',
        account: 'Hope Forward',
        lat: 29.7218,
        lng: -95.4012,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Houston West',
      },
    ],
    zones: [
      {
        lat: 30.2415,
        lng: -97.7689,
        label: 'Austin South · 78704',
        reason: 'Propensity 0.81 · ACS median income $94k · 14% conv (lookalike)',
      },
      {
        lat: 33.0198,
        lng: -96.6989,
        label: 'Plano · 75024',
        reason: 'Propensity 0.78 · lookalike to Highland Park (top cohort)',
      },
      {
        lat: 29.6197,
        lng: -95.6349,
        label: 'Sugar Land · 77479',
        reason: 'Propensity 0.74 · low cannibalisation w/ Houston SE',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // World Vision · AU charity · 12 reps across Syd/Mel/Bne
  // ─────────────────────────────────────────────────────────────────────────
  'world-vision': {
    center: [-32.5, 148.0],
    zoom: 5,
    scopeLabel: 'World Vision AU',
    reps: [
      // Sydney cluster (-33.87, 151.21) — 4 reps
      {
        id: 'wv1',
        initials: 'AC',
        name: 'Amelia Chen',
        account: 'World Vision',
        lat: -33.8688,
        lng: 151.2093,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 45m',
        knocksToday: 72,
        conversionsToday: 21,
        lastKnockMin: 2,
        territory: 'Sydney CBD',
      },
      {
        id: 'wv2',
        initials: 'LO',
        name: 'Liam O’Brien',
        account: 'World Vision',
        lat: -33.8915,
        lng: 151.1875,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 38m',
        knocksToday: 65,
        conversionsToday: 14,
        lastKnockMin: 5,
        territory: 'Sydney Inner West',
      },
      {
        id: 'wv3',
        initials: 'ZH',
        name: 'Zara Habib',
        account: 'World Vision',
        lat: -33.8434,
        lng: 151.2541,
        status: 'active',
        shiftStart: '10:00',
        hoursToday: '3h 51m',
        knocksToday: 58,
        conversionsToday: 12,
        lastKnockMin: 1,
        territory: 'Sydney East',
      },
      {
        id: 'wv4',
        initials: 'JW',
        name: 'Jack Williams',
        account: 'World Vision',
        lat: -33.9173,
        lng: 151.2354,
        status: 'break',
        shiftStart: '10:00',
        hoursToday: '3h 20m · LUNCH',
        knocksToday: 41,
        conversionsToday: 7,
        lastKnockMin: 35,
        territory: 'Sydney South',
      },

      // Melbourne cluster (-37.81, 144.96) — 4 reps
      {
        id: 'wv5',
        initials: 'IN',
        name: 'Isabel Nguyen',
        account: 'World Vision',
        lat: -37.8136,
        lng: 144.9631,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 12m',
        knocksToday: 78,
        conversionsToday: 18,
        lastKnockMin: 3,
        territory: 'Melbourne CBD',
      },
      {
        id: 'wv6',
        initials: 'HK',
        name: 'Harvey Kapoor',
        account: 'World Vision',
        lat: -37.7989,
        lng: 144.9412,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 05m',
        knocksToday: 81,
        conversionsToday: 22,
        lastKnockMin: 1,
        territory: 'Melbourne North',
      },
      {
        id: 'wv7',
        initials: 'GO',
        name: 'Grace O’Sullivan',
        account: 'World Vision',
        lat: -37.8425,
        lng: 145.0033,
        status: 'active',
        shiftStart: '09:30',
        hoursToday: '4h 18m',
        knocksToday: 69,
        conversionsToday: 15,
        lastKnockMin: 4,
        territory: 'Melbourne East',
      },
      {
        id: 'wv8',
        initials: 'NR',
        name: 'Noah Ricci',
        account: 'World Vision',
        lat: -37.8312,
        lng: 144.9215,
        status: 'idle',
        shiftStart: '09:30',
        hoursToday: '4h 30m',
        knocksToday: 47,
        conversionsToday: 6,
        lastKnockMin: 19,
        territory: 'Melbourne West',
      },

      // Brisbane cluster (-27.47, 153.03) — 4 reps
      {
        id: 'wv9',
        initials: 'EM',
        name: 'Ethan Morrison',
        account: 'World Vision',
        lat: -27.4698,
        lng: 153.0251,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '5h 02m',
        knocksToday: 88,
        conversionsToday: 24,
        lastKnockMin: 2,
        territory: 'Brisbane CBD',
      },
      {
        id: 'wv10',
        initials: 'AS',
        name: 'Ava Singh',
        account: 'World Vision',
        lat: -27.4485,
        lng: 153.0398,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '4h 58m',
        knocksToday: 74,
        conversionsToday: 17,
        lastKnockMin: 6,
        territory: 'Brisbane North',
      },
      {
        id: 'wv11',
        initials: 'MT',
        name: 'Mia Tan',
        account: 'World Vision',
        lat: -27.4901,
        lng: 153.0089,
        status: 'active',
        shiftStart: '08:30',
        hoursToday: '5h 10m',
        knocksToday: 61,
        conversionsToday: 13,
        lastKnockMin: 4,
        territory: 'Brisbane South',
      },
      {
        id: 'wv12',
        initials: 'BC',
        name: 'Ben Castro',
        account: 'World Vision',
        lat: -27.4612,
        lng: 153.0512,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Brisbane East',
      },
    ],
    zones: [
      {
        lat: -33.8174,
        lng: 151.0023,
        label: 'Parramatta · 2150',
        reason: 'Propensity 0.79 · SEIFA decile 9 · large multicultural cohort',
      },
      {
        lat: -37.7693,
        lng: 144.9844,
        label: 'Brunswick · 3056',
        reason: 'Propensity 0.82 · charity supporter density top quintile',
      },
      {
        lat: -27.4015,
        lng: 153.1198,
        label: 'Chermside · 4032',
        reason: 'Propensity 0.76 · CoreLogic AU growth corridor · low saturation',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PestMax · US commercial · 8 reps Dallas / Phoenix / Houston
  // ─────────────────────────────────────────────────────────────────────────
  pestmax: {
    center: [32.0, -103.0],
    zoom: 5,
    scopeLabel: 'PestMax · US',
    reps: [
      // Dallas cluster (32.78, -96.80) — 4 reps
      {
        id: 'pm1',
        initials: 'BC',
        name: 'Bianca Costa',
        account: 'PestMax',
        lat: 32.7767,
        lng: -96.797,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 12m',
        knocksToday: 38,
        conversionsToday: 9,
        lastKnockMin: 12,
        territory: 'Dallas Metro',
      },
      {
        id: 'pm2',
        initials: 'HK',
        name: 'Hiroshi Kato',
        account: 'PestMax',
        lat: 32.7712,
        lng: -96.7826,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 18m',
        knocksToday: 42,
        conversionsToday: 7,
        lastKnockMin: 5,
        territory: 'Dallas North',
      },
      {
        id: 'pm3',
        initials: 'RG',
        name: 'Rafael Gomez',
        account: 'PestMax',
        lat: 32.7895,
        lng: -96.8054,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 02m',
        knocksToday: 51,
        conversionsToday: 11,
        lastKnockMin: 8,
        territory: 'Dallas South',
      },
      {
        id: 'pm4',
        initials: 'SK',
        name: 'Sara Kowalski',
        account: 'PestMax',
        lat: 32.7654,
        lng: -96.8125,
        status: 'break',
        shiftStart: '08:00',
        hoursToday: '4h 45m · LUNCH',
        knocksToday: 29,
        conversionsToday: 4,
        lastKnockMin: 32,
        territory: 'Dallas Metro',
      },

      // Phoenix cluster (33.45, -112.07) — 2 reps
      {
        id: 'pm5',
        initials: 'TN',
        name: 'Tara Nguyen',
        account: 'PestMax',
        lat: 33.4484,
        lng: -112.074,
        status: 'active',
        shiftStart: '07:30',
        hoursToday: '5h 50m',
        knocksToday: 45,
        conversionsToday: 8,
        lastKnockMin: 3,
        territory: 'Phoenix Metro',
      },
      {
        id: 'pm6',
        initials: 'JL',
        name: 'José Luna',
        account: 'PestMax',
        lat: 33.4625,
        lng: -112.0891,
        status: 'idle',
        shiftStart: '07:30',
        hoursToday: '6h 02m',
        knocksToday: 33,
        conversionsToday: 4,
        lastKnockMin: 24,
        territory: 'Phoenix West',
      },

      // Houston cluster (29.76, -95.37) — 2 reps
      {
        id: 'pm7',
        initials: 'AT',
        name: 'Aiden Thomas',
        account: 'PestMax',
        lat: 29.7604,
        lng: -95.3698,
        status: 'active',
        shiftStart: '08:00',
        hoursToday: '5h 08m',
        knocksToday: 48,
        conversionsToday: 9,
        lastKnockMin: 6,
        territory: 'Houston SE',
      },
      {
        id: 'pm8',
        initials: 'DG',
        name: 'Diana Gallagher',
        account: 'PestMax',
        lat: 29.7515,
        lng: -95.3812,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Houston SE',
      },
    ],
    zones: [
      {
        lat: 32.8136,
        lng: -96.6483,
        label: 'Garland · 75040',
        reason: 'Propensity 0.71 · termite hotspot · high SFR density',
      },
      {
        lat: 33.4942,
        lng: -111.926,
        label: 'Scottsdale · 85251',
        reason: 'Propensity 0.74 · premium service tier · low cannibalisation',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Gold Coast Hospital · AU healthcare · 8 reps on the Gold Coast
  // ─────────────────────────────────────────────────────────────────────────
  'gold-coast-hospital': {
    center: [-28.02, 153.4],
    zoom: 11,
    scopeLabel: 'Gold Coast Hospital · AU',
    reps: [
      // Surfers Paradise (-28.00, 153.43) — 2 reps
      {
        id: 'gc1',
        initials: 'CO',
        name: 'Charlotte O’Connor',
        account: 'Gold Coast Hospital',
        lat: -28.0033,
        lng: 153.4297,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 05m',
        knocksToday: 52,
        conversionsToday: 6,
        lastKnockMin: 2,
        territory: 'Surfers Paradise',
      },
      {
        id: 'gc2',
        initials: 'JK',
        name: 'James Karras',
        account: 'Gold Coast Hospital',
        lat: -28.0095,
        lng: 153.4258,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 12m',
        knocksToday: 47,
        conversionsToday: 5,
        lastKnockMin: 4,
        territory: 'Surfers Paradise',
      },

      // Broadbeach (-28.03, 153.43) — 2 reps
      {
        id: 'gc3',
        initials: 'EH',
        name: 'Ella Henderson',
        account: 'Gold Coast Hospital',
        lat: -28.029,
        lng: 153.4351,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 08m',
        knocksToday: 44,
        conversionsToday: 5,
        lastKnockMin: 6,
        territory: 'Broadbeach',
      },
      {
        id: 'gc4',
        initials: 'OP',
        name: 'Owen Park',
        account: 'Gold Coast Hospital',
        lat: -28.0354,
        lng: 153.4289,
        status: 'break',
        shiftStart: '09:00',
        hoursToday: '3h 50m · LUNCH',
        knocksToday: 31,
        conversionsToday: 3,
        lastKnockMin: 29,
        territory: 'Broadbeach',
      },

      // Burleigh Heads (-28.10, 153.45) — 1 rep
      {
        id: 'gc5',
        initials: 'MC',
        name: 'Maya Choudhury',
        account: 'Gold Coast Hospital',
        lat: -28.0995,
        lng: 153.4503,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 15m',
        knocksToday: 38,
        conversionsToday: 4,
        lastKnockMin: 3,
        territory: 'Burleigh Heads',
      },

      // Robina (-28.08, 153.39) — 2 reps
      {
        id: 'gc6',
        initials: 'SR',
        name: 'Sienna Roberts',
        account: 'Gold Coast Hospital',
        lat: -28.0815,
        lng: 153.3899,
        status: 'active',
        shiftStart: '09:00',
        hoursToday: '4h 02m',
        knocksToday: 40,
        conversionsToday: 6,
        lastKnockMin: 5,
        territory: 'Robina',
      },
      {
        id: 'gc7',
        initials: 'LD',
        name: 'Lachlan Diaz',
        account: 'Gold Coast Hospital',
        lat: -28.0762,
        lng: 153.3954,
        status: 'idle',
        shiftStart: '09:00',
        hoursToday: '4h 22m',
        knocksToday: 25,
        conversionsToday: 2,
        lastKnockMin: 20,
        territory: 'Robina',
      },

      // Southport (-27.97, 153.40) — 1 rep
      {
        id: 'gc8',
        initials: 'PA',
        name: 'Priya Anand',
        account: 'Gold Coast Hospital',
        lat: -27.9667,
        lng: 153.4034,
        status: 'offline',
        shiftStart: '—',
        hoursToday: 'Not clocked in',
        knocksToday: 0,
        conversionsToday: 0,
        lastKnockMin: 999,
        territory: 'Southport',
      },
    ],
    zones: [
      {
        lat: -28.0421,
        lng: 153.4019,
        label: 'Mermaid Waters · 4218',
        reason: 'Propensity 0.78 · SEIFA decile 9 · capital campaign lookalike',
      },
      {
        lat: -28.0226,
        lng: 153.3672,
        label: 'Nerang · 4211',
        reason: 'Propensity 0.71 · low saturation · family households · catchment 12k doors',
      },
    ],
  },
};

export function getAccountFleet(slug: string): AccountFleetData | undefined {
  return ACCOUNT_FLEET[slug];
}
