/**
 * US cooling-off window data for door-to-door solicitation.
 *
 * Baseline: FTC Door-to-Door Sales Rule (16 CFR Part 429) — 3 business days
 * for sales/subscriptions ≥ $25 made at the consumer's home or other off-premise
 * location. Seller MUST provide a written notice of right to cancel at the time
 * of the transaction.
 *
 * For charitable fundraising the FTC rule applies to signed recurring-gift
 * agreements made at the door (treated as "services contracts"). Some states
 * layer additional charity-specific disclosure requirements.
 *
 * Sources:
 *   - FTC 16 CFR Part 429
 *   - Per-state home-solicitation laws (compiled 2026-06)
 *
 * Update cadence: review quarterly via counsel; any state change requires a code
 * deploy + audit entry — do not edit without legal review.
 */

export interface CoolingOffWindow {
  /** ISO 3166-2:US state/territory code (without country prefix). */
  state: string;
  /** Full state name. */
  stateName: string;
  /** Calendar business days the consumer has to cancel. */
  businessDays: number;
  /** Minimum transaction amount in cents before the rule applies (FTC: 2500 = $25). */
  minimumAmountCents: number;
  /** Seller must give written cancellation-right notice at time of sale. */
  disclosureRequired: boolean;
  /**
   * True when the state's statute explicitly extends or modifies the FTC baseline
   * for door-to-door charitable solicitations.
   */
  charitySpecificExtension: boolean;
  /** Statute or rule reference. */
  source: string;
  /** Any counsel-flagged caveats for this jurisdiction. */
  notes: string | null;
}

/**
 * All 50 US states + DC. The FTC baseline applies in every jurisdiction;
 * rows below note only where state law layers an extension or nuance.
 */
export const COOLING_OFF_WINDOWS: CoolingOffWindow[] = [
  {
    state: 'AL',
    stateName: 'Alabama',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Ala. Code § 8-19-1',
    notes: null,
  },
  {
    state: 'AK',
    stateName: 'Alaska',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Alaska Stat. § 45.45.300',
    notes: null,
  },
  {
    state: 'AZ',
    stateName: 'Arizona',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + A.R.S. § 44-5001',
    notes: null,
  },
  {
    state: 'AR',
    stateName: 'Arkansas',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Ark. Code Ann. § 4-92-101',
    notes: null,
  },
  {
    state: 'CA',
    stateName: 'California',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: true,
    source: 'FTC 16 CFR Part 429 + Cal. Bus. & Prof. Code § 1689.5',
    notes:
      'CA also requires notice in the language used in the sales negotiation. Charity solicitors must be registered with AG before the window runs.',
  },
  {
    state: 'CO',
    stateName: 'Colorado',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + C.R.S. § 6-1-301',
    notes: null,
  },
  {
    state: 'CT',
    stateName: 'Connecticut',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Conn. Gen. Stat. § 42-135a',
    notes: null,
  },
  {
    state: 'DE',
    stateName: 'Delaware',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + 6 Del. C. § 2501',
    notes: null,
  },
  {
    state: 'DC',
    stateName: 'District of Columbia',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + D.C. Code § 28-3811',
    notes: null,
  },
  {
    state: 'FL',
    stateName: 'Florida',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: true,
    source: 'FTC 16 CFR Part 429 + Fla. Stat. § 501.025',
    notes:
      'FL Charitable Solicitations Act requires conspicuous disclosure of the right to cancel at the door.',
  },
  {
    state: 'GA',
    stateName: 'Georgia',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + O.C.G.A. § 10-1-6',
    notes: null,
  },
  {
    state: 'HI',
    stateName: 'Hawaii',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Haw. Rev. Stat. § 481B-1',
    notes: null,
  },
  {
    state: 'ID',
    stateName: 'Idaho',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Idaho Code § 48-601',
    notes: null,
  },
  {
    state: 'IL',
    stateName: 'Illinois',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + 815 ILCS 505/2C',
    notes: null,
  },
  {
    state: 'IN',
    stateName: 'Indiana',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Ind. Code § 24-5-10-1',
    notes: null,
  },
  {
    state: 'IA',
    stateName: 'Iowa',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Iowa Code § 555A.1',
    notes: null,
  },
  {
    state: 'KS',
    stateName: 'Kansas',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + K.S.A. § 50-640',
    notes: null,
  },
  {
    state: 'KY',
    stateName: 'Kentucky',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + KRS § 367.410',
    notes: null,
  },
  {
    state: 'LA',
    stateName: 'Louisiana',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + La. R.S. § 9:3538',
    notes: null,
  },
  {
    state: 'ME',
    stateName: 'Maine',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + 32 M.R.S.A. § 14716',
    notes: null,
  },
  {
    state: 'MD',
    stateName: 'Maryland',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Md. Code Ann., Com. Law § 14-301',
    notes: null,
  },
  {
    state: 'MA',
    stateName: 'Massachusetts',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + M.G.L. c. 93 § 48',
    notes: null,
  },
  {
    state: 'MI',
    stateName: 'Michigan',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + M.C.L.A. § 445.111',
    notes: null,
  },
  {
    state: 'MN',
    stateName: 'Minnesota',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Minn. Stat. § 325G.06',
    notes: null,
  },
  {
    state: 'MS',
    stateName: 'Mississippi',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Miss. Code Ann. § 75-66-1',
    notes: null,
  },
  {
    state: 'MO',
    stateName: 'Missouri',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Mo. Rev. Stat. § 407.700',
    notes: null,
  },
  {
    state: 'MT',
    stateName: 'Montana',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Mont. Code Ann. § 30-14-501',
    notes: null,
  },
  {
    state: 'NE',
    stateName: 'Nebraska',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Neb. Rev. Stat. § 69-1201',
    notes: null,
  },
  {
    state: 'NV',
    stateName: 'Nevada',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + NRS § 598.090',
    notes: null,
  },
  {
    state: 'NH',
    stateName: 'New Hampshire',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + N.H. Rev. Stat. Ann. § 361-B:1',
    notes: null,
  },
  {
    state: 'NJ',
    stateName: 'New Jersey',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: true,
    source: 'FTC 16 CFR Part 429 + N.J. Stat. Ann. § 56:8-26',
    notes:
      'NJ requires a copy of the cancellation notice in the same language used in the solicitation.',
  },
  {
    state: 'NM',
    stateName: 'New Mexico',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + N.M. Stat. Ann. § 57-12-22',
    notes: null,
  },
  {
    state: 'NY',
    stateName: 'New York',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: true,
    source: 'FTC 16 CFR Part 429 + N.Y. Pers. Prop. Law § 425',
    notes:
      'NY AG requires charitable solicitation annual reports. NY cooling-off notice must be provided in the same language as the solicitation.',
  },
  {
    state: 'NC',
    stateName: 'North Carolina',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + N.C. Gen. Stat. § 25A-39',
    notes: null,
  },
  {
    state: 'ND',
    stateName: 'North Dakota',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + N.D. Cent. Code § 51-18-01',
    notes: null,
  },
  {
    state: 'OH',
    stateName: 'Ohio',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Ohio Rev. Code § 1345.21',
    notes: null,
  },
  {
    state: 'OK',
    stateName: 'Oklahoma',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Okla. Stat. tit. 15 § 751',
    notes: null,
  },
  {
    state: 'OR',
    stateName: 'Oregon',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + ORS § 83.710',
    notes: null,
  },
  {
    state: 'PA',
    stateName: 'Pennsylvania',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + 73 Pa. Cons. Stat. § 201-7',
    notes: null,
  },
  {
    state: 'RI',
    stateName: 'Rhode Island',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + R.I. Gen. Laws § 6-28-1',
    notes: null,
  },
  {
    state: 'SC',
    stateName: 'South Carolina',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + S.C. Code Ann. § 39-45-10',
    notes: null,
  },
  {
    state: 'SD',
    stateName: 'South Dakota',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + S.D. Codified Laws § 37-24-1',
    notes: null,
  },
  {
    state: 'TN',
    stateName: 'Tennessee',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Tenn. Code Ann. § 47-18-702',
    notes: null,
  },
  {
    state: 'TX',
    stateName: 'Texas',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Tex. Bus. & Com. Code § 39.001',
    notes: null,
  },
  {
    state: 'UT',
    stateName: 'Utah',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Utah Code Ann. § 70C-5-103',
    notes: null,
  },
  {
    state: 'VT',
    stateName: 'Vermont',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + 9 V.S.A. § 2454',
    notes: null,
  },
  {
    state: 'VA',
    stateName: 'Virginia',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Va. Code Ann. § 59.1-21.2',
    notes: null,
  },
  {
    state: 'WA',
    stateName: 'Washington',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: true,
    source: 'FTC 16 CFR Part 429 + RCW 19.86',
    notes:
      'WA Charitable Solicitations Act (RCW ch. 19.09) requires registered professional solicitors to disclose the right to cancel on every written confirmation.',
  },
  {
    state: 'WV',
    stateName: 'West Virginia',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + W. Va. Code § 46A-6D-1',
    notes: null,
  },
  {
    state: 'WI',
    stateName: 'Wisconsin',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Wis. Stat. § 423.201',
    notes: null,
  },
  {
    state: 'WY',
    stateName: 'Wyoming',
    businessDays: 3,
    minimumAmountCents: 2500,
    disclosureRequired: true,
    charitySpecificExtension: false,
    source: 'FTC 16 CFR Part 429 + Wyo. Stat. Ann. § 40-12-201',
    notes: null,
  },
];

/** Keyed by state code for O(1) lookup. */
export const COOLING_OFF_BY_STATE = new Map<string, CoolingOffWindow>(
  COOLING_OFF_WINDOWS.map((w) => [w.state, w]),
);
