import { EmptyState, KpiCard, Money, Section, StatusPill } from '@d2d/ui-web';
import { PortalShell } from '@/components/PortalShell';
import { payoutLabel, payoutTone } from '@/lib/status';
import { apiFetch, getSession, sumWireCents, wireCents, type PayoutBatchPublic } from '@/lib/api';

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

const DOWNLOADABLE: PayoutBatchPublic['status'][] = ['ready_to_pay', 'instructed'];

export default async function PayoutsPage(): Promise<JSX.Element> {
  const { user, org } = await getSession();
  const { batches } = await apiFetch<{ batches: PayoutBatchPublic[]; nextCursor: string | null }>(
    '/payout-batches?limit=50',
  );

  const totalCents = sumWireCents(batches, (b) => b.totalCents);
  const latest = batches[0] ?? null;

  return (
    <PortalShell
      pageTitle="Payout statements"
      orgName={org.tradingName}
      userName={`${user.givenName} ${user.familyName}`}
      userEmail={user.email}
      userRole={user.role}
    >
      <div className="space-y-6">
        <Section title="Overview">
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <KpiCard
              label="Total across batches"
              value={<Money cents={totalCents} region={org.regionCode} />}
              hint={`${batches.length} batch${batches.length === 1 ? '' : 'es'}`}
              animate={false}
            />
            <KpiCard
              label="Latest batch"
              value={latest ? payoutLabel(latest.status) : '—'}
              hint={latest ? fmtDate(latest.periodStart) : 'no batches yet'}
            />
            <KpiCard
              label="Commission lines"
              value={latest ? String(latest.lineCount) : '—'}
              hint="latest batch"
            />
          </div>
        </Section>

        <Section title="Payout batch history" paddedBody={batches.length === 0}>
          {batches.length === 0 ? (
            <EmptyState
              title="No payout batches yet"
              description="Batches appear here once D2D generates a payout run from accrued commissions."
            />
          ) : (
            <div className="tbl-wrapper">
              <table className="tbl">
                <thead>
                  <tr>
                    <th>Period</th>
                    <th>Status</th>
                    <th className="text-right">Lines</th>
                    <th className="text-right">Total</th>
                    <th />
                  </tr>
                </thead>
                <tbody>
                  {batches.map((b) => (
                    <tr key={b.id}>
                      <td className="font-medium">
                        {fmtDate(b.periodStart)} – {fmtDate(b.periodEnd)}
                      </td>
                      <td>
                        <StatusPill tone={payoutTone(b.status)}>{payoutLabel(b.status)}</StatusPill>
                      </td>
                      <td className="text-right mono">{b.lineCount}</td>
                      <td className="text-right mono font-medium">
                        <Money cents={wireCents(b.totalCents)} region={org.regionCode} />
                      </td>
                      <td className="text-right">
                        {DOWNLOADABLE.includes(b.status) ? (
                          <a
                            href={`/proxy/api/payout-batches/${b.id}/instruction-file`}
                            className="text-[12px] text-accent hover:underline"
                          >
                            Download CSV
                          </a>
                        ) : (
                          <span className="text-[12px] text-soft">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Section>

        <Section title="Important — payout process">
          <div className="card p-5 text-sm text-muted leading-relaxed max-w-3xl space-y-3">
            <p>
              <strong className="text-ink">D2D never auto-debits.</strong> Payout batches are
              generated by the platform and downloaded as a CSV instruction file. D2D executes each
              transfer manually via the banking portal — the platform only ever instructs, never
              moves funds itself.
            </p>
            <p>
              <strong className="text-ink">Lifecycle:</strong> a batch moves draft → ready to pay →
              instructed (once the instruction file is downloaded) → acknowledged.
            </p>
            <p>
              <strong className="text-ink">Questions:</strong> contact{' '}
              <span className="text-accent">payouts@door2digital.io</span> with the batch ID and the
              line item in question.
            </p>
          </div>
        </Section>
      </div>
    </PortalShell>
  );
}
