import { PartnerShell } from '@/components/PartnerShell';
import { Section, StatusPill, KpiCard } from '@d2d/ui-web';
import { Download } from 'lucide-react';
import { PAYOUT_STATEMENTS } from '@/lib/fixtures';

function formatCents(cents: number): string {
  return `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
}

function statusLabel(s: string): string {
  if (s === 'acknowledged') return 'Acknowledged';
  if (s === 'instructed') return 'Instructed';
  return 'Ready';
}

function statusTone(s: string): 'success' | 'warn' | 'muted' {
  if (s === 'acknowledged') return 'success';
  if (s === 'instructed') return 'warn';
  return 'muted';
}

export default function PayoutsPage() {
  const total = PAYOUT_STATEMENTS.reduce((a, p) => a + p.totalCents, 0);
  const latestKnockers = PAYOUT_STATEMENTS[0]!.knockerCount;

  return (
    <PartnerShell pageTitle="Payout statements">
      <div className="space-y-6">
        <Section title="Overview">
          <div className="grid grid-cols-3 gap-4">
            <KpiCard
              label="YTD payout total"
              value={formatCents(total)}
              hint="Across all periods"
            />
            <KpiCard
              label="Active knockers"
              value={String(latestKnockers)}
              hint="Last pay period"
            />
            <KpiCard label="Pay schedule" value="Fortnightly" hint="1st + 16th of each month" />
          </div>
        </Section>

        <Section title="Payout statement history">
          <div className="tbl-wrapper">
            <table className="tbl">
              <thead>
                <tr>
                  <th>Period</th>
                  <th>Generated</th>
                  <th>Status</th>
                  <th className="text-right">Knockers</th>
                  <th className="text-right">Total</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {PAYOUT_STATEMENTS.map((ps) => (
                  <tr key={ps.id}>
                    <td className="font-medium">{ps.period}</td>
                    <td className="text-muted">{ps.generatedDate}</td>
                    <td>
                      <StatusPill tone={statusTone(ps.status)}>{statusLabel(ps.status)}</StatusPill>
                    </td>
                    <td className="text-right mono">{ps.knockerCount}</td>
                    <td className="text-right mono font-medium">{formatCents(ps.totalCents)}</td>
                    <td>
                      <button
                        className="flex items-center gap-1 text-xs text-accent hover:underline"
                        onClick={() =>
                          alert(
                            `Download CSV for ${ps.id} — wired to /v1/payout-batches/${ps.id}/instruction-file`,
                          )
                        }
                      >
                        <Download size={12} />
                        CSV
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        <Section title="Important — payout process">
          <div className="card p-5 text-sm text-muted leading-relaxed max-w-3xl space-y-3">
            <p>
              <strong className="text-ink">D2D never auto-debits.</strong> Payout batches are
              generated by the platform and downloaded as a CSV instruction file. Brodie at D2D
              executes each transfer manually via the banking portal.
            </p>
            <p>
              <strong className="text-ink">Timing:</strong> batches are generated on the 1st and
              16th of each month covering the prior two-week period. Knockers receive funds within 2
              business days of the batch being acknowledged.
            </p>
            <p>
              <strong className="text-ink">Disputes:</strong> knockers can dispute their statement
              within 7 days of generation. Contact{' '}
              <span className="text-accent">payouts@door2digital.io</span> with your batch ID and
              the specific line item in question.
            </p>
          </div>
        </Section>
      </div>
    </PartnerShell>
  );
}
